packages:
  - .
  - examples

catalog:
  '@ai-sdk/provider-utils': ^3.0.18
  nano-spawn: ^2.0.0

catalogMode: strict

catalogs:
  ai:
    '@ai-sdk/openai': ^2.0.46
    ai: ^5.0.63
    openai: ^6.2.0
  build:
    tsdown: ^0.15.9
    unplugin-unused: ^0.5.4
  lint:
    '@biomejs/biome': ^1.5.3
    lint-staged: ^15.2.0
    publint: ^0.3.12
  other:
    '@hono/mcp': ^0.1.4
    hono: ^4.9.10
    mkdocs: ^0.0.1
    openapi-types: ^12.1.3
    tsx: ^4.19.4
    zod: ^3.23.8
  runtime:
    '@modelcontextprotocol/sdk': ^1.19.1
    '@orama/orama': ^3.1.11
    '@stackone/stackone-client-ts': 4.32.2
    json-schema: ^0.4.0
  testing:
    '@vitest/coverage-v8': ^3.2.4
    fs-fixture: ^2.8.1
    msw: ^2.10.4
    vitest: ^3.2.4
  types:
    '@types/bun': ^1.2.4
    '@types/json-schema': ^7.0.15
    '@types/node': ^22.13.5
    '@typescript/native-preview': ^7.0.0-dev.20251202.1
    type-fest: ^4.41.0
    typescript: ^5.8.3

enablePrePostScripts: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@stackone/stackone-client-ts'

onlyBuiltDependencies:
  - '@biomejs/biome'
  - esbuild
  - msw

shellEmulator: true
