// Auto-generated by StackOneToolSet.generateTypedClient()
// DO NOT EDIT THIS FILE DIRECTLY

import type { DynamicToolClient } from '@stackone/ai';
import type {
  JsonDict,
  UnifiedHrisListEmployeesParams,
  UnifiedHrisGetEmployeesParams,
  UnifiedHrisCreateEmployeesParams,
  UnifiedHrisUpdateEmployeesParams,
  UnifiedHrisListEmployeesDocumentsParams,
  UnifiedHrisGetEmployeesDocumentsParams,
  UnifiedHrisDownloadEmployeesDocumentsParams,
  UnifiedHrisListEmployeesWorkEligibilityParams,
  UnifiedHrisGetEmployeesWorkEligibilityParams,
  UnifiedHrisUpdateEmployeesWorkEligibilityParams,
  UnifiedHrisListEmployeesEmploymentsParams,
  UnifiedHrisGetEmployeesEmploymentsParams,
  UnifiedHrisListEmploymentsParams,
  UnifiedHrisGetEmploymentsParams,
  UnifiedHrisListLocationsParams,
  UnifiedHrisGetLocationsParams,
  UnifiedHrisListDocumentsEmployeeCategoriesParams,
  UnifiedHrisGetDocumentsEmployeeCategoriesParams,
  UnifiedHrisListGroupsDepartmentsParams,
  UnifiedHrisGetGroupsDepartmentsParams,
  UnifiedHrisListCustomFieldDefinitionsEmployeesParams,
  UnifiedHrisGetCustomFieldDefinitionsEmployeesParams
} from './types';

export async function unifiedHrisListEmployees(client: DynamicToolClient, params: UnifiedHrisListEmployeesParams): Promise<JsonDict> {
  return client.execute('unified_hris_list_employees', params);
}

export async function unifiedHrisGetEmployees(client: DynamicToolClient, params: UnifiedHrisGetEmployeesParams): Promise<JsonDict> {
  return client.execute('unified_hris_get_employees', params);
}

export async function unifiedHrisCreateEmployees(client: DynamicToolClient, params: UnifiedHrisCreateEmployeesParams): Promise<JsonDict> {
  return client.execute('unified_hris_create_employees', params);
}

export async function unifiedHrisUpdateEmployees(client: DynamicToolClient, params: UnifiedHrisUpdateEmployeesParams): Promise<JsonDict> {
  return client.execute('unified_hris_update_employees', params);
}

export async function unifiedHrisListEmployeesDocuments(client: DynamicToolClient, params: UnifiedHrisListEmployeesDocumentsParams): Promise<JsonDict> {
  return client.execute('unified_hris_list_employees_documents', params);
}

export async function unifiedHrisGetEmployeesDocuments(client: DynamicToolClient, params: UnifiedHrisGetEmployeesDocumentsParams): Promise<JsonDict> {
  return client.execute('unified_hris_get_employees_documents', params);
}

export async function unifiedHrisDownloadEmployeesDocuments(client: DynamicToolClient, params: UnifiedHrisDownloadEmployeesDocumentsParams): Promise<JsonDict> {
  return client.execute('unified_hris_download_employees_documents', params);
}

export async function unifiedHrisListEmployeesWorkEligibility(client: DynamicToolClient, params: UnifiedHrisListEmployeesWorkEligibilityParams): Promise<JsonDict> {
  return client.execute('unified_hris_list_employees_work_eligibility', params);
}

export async function unifiedHrisGetEmployeesWorkEligibility(client: DynamicToolClient, params: UnifiedHrisGetEmployeesWorkEligibilityParams): Promise<JsonDict> {
  return client.execute('unified_hris_get_employees_work_eligibility', params);
}

export async function unifiedHrisUpdateEmployeesWorkEligibility(client: DynamicToolClient, params: UnifiedHrisUpdateEmployeesWorkEligibilityParams): Promise<JsonDict> {
  return client.execute('unified_hris_update_employees_work_eligibility', params);
}

export async function unifiedHrisListEmployeesEmployments(client: DynamicToolClient, params: UnifiedHrisListEmployeesEmploymentsParams): Promise<JsonDict> {
  return client.execute('unified_hris_list_employees_employments', params);
}

export async function unifiedHrisGetEmployeesEmployments(client: DynamicToolClient, params: UnifiedHrisGetEmployeesEmploymentsParams): Promise<JsonDict> {
  return client.execute('unified_hris_get_employees_employments', params);
}

export async function unifiedHrisListEmployments(client: DynamicToolClient, params: UnifiedHrisListEmploymentsParams): Promise<JsonDict> {
  return client.execute('unified_hris_list_employments', params);
}

export async function unifiedHrisGetEmployments(client: DynamicToolClient, params: UnifiedHrisGetEmploymentsParams): Promise<JsonDict> {
  return client.execute('unified_hris_get_employments', params);
}

export async function unifiedHrisListLocations(client: DynamicToolClient, params: UnifiedHrisListLocationsParams): Promise<JsonDict> {
  return client.execute('unified_hris_list_locations', params);
}

export async function unifiedHrisGetLocations(client: DynamicToolClient, params: UnifiedHrisGetLocationsParams): Promise<JsonDict> {
  return client.execute('unified_hris_get_locations', params);
}

export async function unifiedHrisListDocumentsEmployeeCategories(client: DynamicToolClient, params: UnifiedHrisListDocumentsEmployeeCategoriesParams): Promise<JsonDict> {
  return client.execute('unified_hris_list_documents_employee_categories', params);
}

export async function unifiedHrisGetDocumentsEmployeeCategories(client: DynamicToolClient, params: UnifiedHrisGetDocumentsEmployeeCategoriesParams): Promise<JsonDict> {
  return client.execute('unified_hris_get_documents_employee_categories', params);
}

export async function unifiedHrisListGroupsDepartments(client: DynamicToolClient, params: UnifiedHrisListGroupsDepartmentsParams): Promise<JsonDict> {
  return client.execute('unified_hris_list_groups_departments', params);
}

export async function unifiedHrisGetGroupsDepartments(client: DynamicToolClient, params: UnifiedHrisGetGroupsDepartmentsParams): Promise<JsonDict> {
  return client.execute('unified_hris_get_groups_departments', params);
}

export async function unifiedHrisListCustomFieldDefinitionsEmployees(client: DynamicToolClient, params: UnifiedHrisListCustomFieldDefinitionsEmployeesParams): Promise<JsonDict> {
  return client.execute('unified_hris_list_custom_field_definitions_employees', params);
}

export async function unifiedHrisGetCustomFieldDefinitionsEmployees(client: DynamicToolClient, params: UnifiedHrisGetCustomFieldDefinitionsEmployeesParams): Promise<JsonDict> {
  return client.execute('unified_hris_get_custom_field_definitions_employees', params);
}
