// Auto-generated TypeScript SDK from OpenAPI specification
// DO NOT EDIT THIS FILE DIRECTLY

import type { StackOneClientConfig } from './types';

// ============================================================
// Type Definitions
// ============================================================

// Auto-generated TypeScript interfaces from OpenAPI schemas
// DO NOT EDIT THIS FILE DIRECTLY

export interface BadGatewayResponse {
  /** HTTP status code */
  statusCode: number;
  /** Error message */
  message: string;
  /** Timestamp when the error occurred */
  timestamp: string;
}

export interface BadRequestResponse {
  /** HTTP status code */
  statusCode: number;
  /** Error message */
  message: string;
  /** Timestamp when the error occurred */
  timestamp: string;
  /** Error details */
  data?: UnifiedError | null;
  /** List of provider-specific errors */
  provider_errors?: ProviderError[] | null;
}

export interface ConfidentialEnumApiModel {
  /** Whether the file is confidential or not */
  value?: 'true' | 'false' | 'unmapped_value' | null;
  source_value?: (string | number | boolean | Record<string, unknown> | unknown[]) | null;
}

export interface ConflictResponse {
  /** HTTP status code */
  statusCode: number;
  /** Error message */
  message: string;
  /** Timestamp when the error occurred */
  timestamp: string;
}

export interface DownloadApiModel {
  /** Headers related to the download */
  headers: DownloadHeadersApiModel;
  /** The file data in binary format */
  data: string;
}

export interface DownloadHeadersApiModel {
  /** Value of the Content-Disposition header */
  'content-disposition'?: string | null;
  /** MIME type of the file */
  'content-type'?: string | null;
  /** Size of the content in bytes */
  'content-length'?: number | null;
  /** Range of the content being sent */
  'content-range'?: string | null;
  /** Encoding of the content */
  'content-encoding'?: string | null;
  /** Transfer encoding type */
  'transfer-encoding'?: string | null;
}

export interface DriveResult {
  data: Drives;
  raw?: RawResponse[] | null;
}

export interface Drives {
  /** The ID associated with this drive */
  id?: string | null;
  /** Provider's unique identifier */
  remote_id?: string | null;
  /** The name associated with this drive */
  name?: string | null;
  /** The description associated with this drive */
  description?: string | null;
  /** The url of the drive */
  url?: string | null;
  /** The created date of the drive */
  created_at?: string | null;
  /** The last updated date of the drive */
  updated_at?: string | null;
}

export interface DrivesPaginated {
  next?: string | null;
  data: Drives[];
  raw?: RawResponse[] | null;
}

export interface FileFormatEnum {
  /** The file format of the file, expressed as a file extension */
  value?:
    | 'unmapped_value'
    | 'ez'
    | 'aw'
    | 'atom'
    | 'atomcat'
    | 'atomdeleted'
    | 'atomsvc'
    | 'dwd'
    | 'held'
    | 'rsat'
    | 'bdoc'
    | 'xcs'
    | 'ccxml'
    | 'cdfx'
    | 'cdmia'
    | 'cdmic'
    | 'cdmid'
    | 'cdmio'
    | 'cdmiq'
    | 'cu'
    | 'mpd'
    | 'davmount'
    | 'dbk'
    | 'dssc'
    | 'xdssc'
    | 'es'
    | 'ecma'
    | 'emma'
    | 'emotionml'
    | 'epub'
    | 'exi'
    | 'exp'
    | 'fdt'
    | 'pfr'
    | 'geojson'
    | 'gml'
    | 'gpx'
    | 'gxf'
    | 'gz'
    | 'hjson'
    | 'stk'
    | 'ink'
    | 'inkml'
    | 'ipfix'
    | 'its'
    | 'jar'
    | 'war'
    | 'ear'
    | 'ser'
    | 'class'
    | 'js'
    | 'mjs'
    | 'json'
    | 'map'
    | 'json5'
    | 'jsonml'
    | 'jsonld'
    | 'lgr'
    | 'lostxml'
    | 'hqx'
    | 'cpt'
    | 'mads'
    | 'webmanifest'
    | 'mrc'
    | 'mrcx'
    | 'ma'
    | 'nb'
    | 'mb'
    | 'mathml'
    | 'mbox'
    | 'mscml'
    | 'metalink'
    | 'meta4'
    | 'mets'
    | 'maei'
    | 'musd'
    | 'mods'
    | 'm21'
    | 'mp21'
    | 'mp4s'
    | 'm4p'
    | 'doc'
    | 'dot'
    | 'mxf'
    | 'nq'
    | 'nt'
    | 'cjs'
    | 'bin'
    | 'dms'
    | 'lrf'
    | 'mar'
    | 'so'
    | 'dist'
    | 'distz'
    | 'pkg'
    | 'bpk'
    | 'dump'
    | 'elc'
    | 'deploy'
    | 'exe'
    | 'dll'
    | 'deb'
    | 'dmg'
    | 'iso'
    | 'img'
    | 'msi'
    | 'msp'
    | 'msm'
    | 'buffer'
    | 'oda'
    | 'opf'
    | 'ogx'
    | 'omdoc'
    | 'onetoc'
    | 'onetoc2'
    | 'onetmp'
    | 'onepkg'
    | 'oxps'
    | 'relo'
    | 'xer'
    | 'pdf'
    | 'pgp'
    | 'asc'
    | 'sig'
    | 'prf'
    | 'p10'
    | 'p7m'
    | 'p7c'
    | 'p7s'
    | 'p8'
    | 'ac'
    | 'cer'
    | 'crl'
    | 'pkipath'
    | 'pki'
    | 'pls'
    | 'ai'
    | 'eps'
    | 'ps'
    | 'provx'
    | 'pskcxml'
    | 'raml'
    | 'rdf'
    | 'owl'
    | 'rif'
    | 'rnc'
    | 'rl'
    | 'rld'
    | 'rs'
    | 'rapd'
    | 'sls'
    | 'rusd'
    | 'gbr'
    | 'mft'
    | 'roa'
    | 'rsd'
    | 'rss'
    | 'rtf'
    | 'sbml'
    | 'scq'
    | 'scs'
    | 'spq'
    | 'spp'
    | 'sdp'
    | 'senmlx'
    | 'sensmlx'
    | 'setpay'
    | 'setreg'
    | 'shf'
    | 'siv'
    | 'sieve'
    | 'smi'
    | 'smil'
    | 'rq'
    | 'srx'
    | 'gram'
    | 'grxml'
    | 'sru'
    | 'ssdl'
    | 'ssml'
    | 'swidtag'
    | 'tei'
    | 'teicorpus'
    | 'tfi'
    | 'tsd'
    | 'toml'
    | 'trig'
    | 'ttml'
    | 'ubj'
    | 'rsheet'
    | 'td'
    | 'vxml'
    | 'wasm'
    | 'wgt'
    | 'hlp'
    | 'wsdl'
    | 'wspolicy'
    | 'xaml'
    | 'xav'
    | 'xca'
    | 'xdf'
    | 'xel'
    | 'xns'
    | 'xenc'
    | 'xhtml'
    | 'xht'
    | 'xlf'
    | 'xml'
    | 'xsl'
    | 'xsd'
    | 'rng'
    | 'dtd'
    | 'xop'
    | 'xpl'
    | '*xsl'
    | 'xslt'
    | 'xspf'
    | 'mxml'
    | 'xhvml'
    | 'xvml'
    | 'xvm'
    | 'yang'
    | 'yin'
    | 'zip'
    | '*3gpp'
    | 'adp'
    | 'amr'
    | 'au'
    | 'snd'
    | 'mid'
    | 'midi'
    | 'kar'
    | 'rmi'
    | 'mxmf'
    | '*mp3'
    | 'm4a'
    | 'mp4a'
    | 'mpga'
    | 'mp2'
    | 'mp2a'
    | 'mp3'
    | 'm2a'
    | 'm3a'
    | 'oga'
    | 'ogg'
    | 'spx'
    | 'opus'
    | 's3m'
    | 'sil'
    | 'wav'
    | '*wav'
    | 'weba'
    | 'xm'
    | 'ttc'
    | 'otf'
    | 'ttf'
    | 'woff'
    | 'woff2'
    | 'exr'
    | 'apng'
    | 'avif'
    | 'bmp'
    | 'cgm'
    | 'drle'
    | 'emf'
    | 'fits'
    | 'g3'
    | 'gif'
    | 'heic'
    | 'heics'
    | 'heif'
    | 'heifs'
    | 'hej2'
    | 'hsj2'
    | 'ief'
    | 'jls'
    | 'jp2'
    | 'jpg2'
    | 'jpeg'
    | 'jpg'
    | 'jpe'
    | 'jph'
    | 'jhc'
    | 'jpm'
    | 'jpx'
    | 'jpf'
    | 'jxr'
    | 'jxra'
    | 'jxrs'
    | 'jxs'
    | 'jxsc'
    | 'jxsi'
    | 'jxss'
    | 'ktx'
    | 'ktx2'
    | 'png'
    | 'sgi'
    | 'svg'
    | 'svgz'
    | 't38'
    | 'tif'
    | 'tiff'
    | 'tfx'
    | 'webp'
    | 'wmf'
    | 'disposition-notification'
    | 'u8msg'
    | 'u8dsn'
    | 'u8mdn'
    | 'u8hdr'
    | 'eml'
    | 'mime'
    | '3mf'
    | 'gltf'
    | 'glb'
    | 'igs'
    | 'iges'
    | 'msh'
    | 'mesh'
    | 'silo'
    | 'mtl'
    | 'obj'
    | 'stpx'
    | 'stpz'
    | 'stpxz'
    | 'stl'
    | 'wrl'
    | 'vrml'
    | '*x3db'
    | 'x3dbz'
    | 'x3db'
    | '*x3dv'
    | 'x3dvz'
    | 'x3d'
    | 'x3dz'
    | 'x3dv'
    | 'appcache'
    | 'manifest'
    | 'ics'
    | 'ifb'
    | 'coffee'
    | 'litcoffee'
    | 'css'
    | 'csv'
    | 'html'
    | 'htm'
    | 'shtml'
    | 'jade'
    | 'jsx'
    | 'less'
    | 'markdown'
    | 'md'
    | 'mml'
    | 'mdx'
    | 'n3'
    | 'txt'
    | 'text'
    | 'conf'
    | 'def'
    | 'list'
    | 'log'
    | 'in'
    | 'ini'
    | 'rtx'
    | '*rtf'
    | 'sgml'
    | 'sgm'
    | 'shex'
    | 'slim'
    | 'slm'
    | 'spdx'
    | 'stylus'
    | 'styl'
    | 'tsv'
    | 't'
    | 'tr'
    | 'roff'
    | 'man'
    | 'me'
    | 'ms'
    | 'ttl'
    | 'uri'
    | 'uris'
    | 'urls'
    | 'vcard'
    | 'vtt'
    | '*xml'
    | 'yaml'
    | 'yml'
    | '3gp'
    | '3gpp'
    | '3g2'
    | 'h261'
    | 'h263'
    | 'h264'
    | 'm4s'
    | 'jpgv'
    | '*jpm'
    | 'jpgm'
    | 'mj2'
    | 'mjp2'
    | 'ts'
    | 'mp4'
    | 'mp4v'
    | 'mpg4'
    | 'mpeg'
    | 'mpg'
    | 'mpe'
    | 'm1v'
    | 'm2v'
    | 'ogv'
    | 'qt'
    | 'mov'
    | 'webm'
    | 'cww'
    | '1km'
    | 'plb'
    | 'psb'
    | 'pvb'
    | 'tcap'
    | 'pwn'
    | 'aso'
    | 'imp'
    | 'acu'
    | 'atc'
    | 'acutc'
    | 'air'
    | 'fcdt'
    | 'fxp'
    | 'fxpl'
    | 'xdp'
    | 'xfdf'
    | 'ahead'
    | 'azf'
    | 'azs'
    | 'azw'
    | 'acc'
    | 'ami'
    | 'apk'
    | 'cii'
    | 'fti'
    | 'atx'
    | 'mpkg'
    | 'key'
    | 'm3u8'
    | 'numbers'
    | 'pages'
    | 'pkpass'
    | 'swi'
    | 'iota'
    | 'aep'
    | 'bmml'
    | 'mpm'
    | 'bmi'
    | 'rep'
    | 'cdxml'
    | 'mmd'
    | 'cdy'
    | 'csl'
    | 'cla'
    | 'rp9'
    | 'c4g'
    | 'c4d'
    | 'c4f'
    | 'c4p'
    | 'c4u'
    | 'c11amc'
    | 'c11amz'
    | 'csp'
    | 'cdbcmsg'
    | 'cmc'
    | 'clkx'
    | 'clkk'
    | 'clkp'
    | 'clkt'
    | 'clkw'
    | 'wbs'
    | 'pml'
    | 'ppd'
    | 'car'
    | 'pcurl'
    | 'dart'
    | 'rdz'
    | 'dbf'
    | 'uvf'
    | 'uvvf'
    | 'uvd'
    | 'uvvd'
    | 'uvt'
    | 'uvvt'
    | 'uvx'
    | 'uvvx'
    | 'uvz'
    | 'uvvz'
    | 'fe_launch'
    | 'dna'
    | 'mlp'
    | 'mle'
    | 'dpg'
    | 'dfac'
    | 'kpxx'
    | 'ait'
    | 'svc'
    | 'geo'
    | 'mag'
    | 'nml'
    | 'esf'
    | 'msf'
    | 'qam'
    | 'slt'
    | 'ssf'
    | 'es3'
    | 'et3'
    | 'ez2'
    | 'ez3'
    | 'fdf'
    | 'mseed'
    | 'seed'
    | 'dataless'
    | 'gph'
    | 'ftc'
    | 'fm'
    | 'frame'
    | 'maker'
    | 'book'
    | 'fnc'
    | 'ltf'
    | 'fsc'
    | 'oas'
    | 'oa2'
    | 'oa3'
    | 'fg5'
    | 'bh2'
    | 'ddd'
    | 'xdw'
    | 'xbd'
    | 'fzs'
    | 'txd'
    | 'ggb'
    | 'ggt'
    | 'gex'
    | 'gre'
    | 'gxt'
    | 'g2w'
    | 'g3w'
    | 'gmx'
    | 'gdoc'
    | 'gslides'
    | 'gsheet'
    | 'kml'
    | 'kmz'
    | 'gqf'
    | 'gqs'
    | 'gac'
    | 'ghf'
    | 'gim'
    | 'grv'
    | 'gtm'
    | 'tpl'
    | 'vcg'
    | 'hal'
    | 'zmm'
    | 'hbci'
    | 'les'
    | 'hpgl'
    | 'hpid'
    | 'hps'
    | 'jlt'
    | 'pcl'
    | 'pclxl'
    | 'sfd-hdstx'
    | 'mpy'
    | 'afp'
    | 'listafp'
    | 'list3820'
    | 'irm'
    | 'sc'
    | 'icc'
    | 'icm'
    | 'igl'
    | 'ivp'
    | 'ivu'
    | 'igm'
    | 'xpw'
    | 'xpx'
    | 'i2g'
    | 'qbo'
    | 'qfx'
    | 'rcprofile'
    | 'irp'
    | 'xpr'
    | 'fcs'
    | 'jam'
    | 'rms'
    | 'jisp'
    | 'joda'
    | 'ktz'
    | 'ktr'
    | 'karbon'
    | 'chrt'
    | 'kfo'
    | 'flw'
    | 'kon'
    | 'kpr'
    | 'kpt'
    | 'ksp'
    | 'kwd'
    | 'kwt'
    | 'htke'
    | 'kia'
    | 'kne'
    | 'knp'
    | 'skp'
    | 'skd'
    | 'skt'
    | 'skm'
    | 'sse'
    | 'lasxml'
    | 'lbd'
    | 'lbe'
    | 'apr'
    | 'pre'
    | 'nsf'
    | 'org'
    | 'scm'
    | 'lwp'
    | 'portpkg'
    | 'mvt'
    | 'mcd'
    | 'mc1'
    | 'cdkey'
    | 'mwf'
    | 'mfm'
    | 'flo'
    | 'igx'
    | 'mif'
    | 'daf'
    | 'dis'
    | 'mbk'
    | 'mqy'
    | 'msl'
    | 'plc'
    | 'txf'
    | 'mpn'
    | 'mpc'
    | 'xul'
    | 'cil'
    | 'cab'
    | 'xls'
    | 'xlm'
    | 'xla'
    | 'xlc'
    | 'xlt'
    | 'xlw'
    | 'xlam'
    | 'xlsb'
    | 'xlsm'
    | 'xltm'
    | 'eot'
    | 'chm'
    | 'ims'
    | 'lrm'
    | 'thmx'
    | 'msg'
    | 'cat'
    | '*stl'
    | 'ppt'
    | 'pps'
    | 'pot'
    | 'ppam'
    | 'pptm'
    | 'sldm'
    | 'ppsm'
    | 'potm'
    | 'mpp'
    | 'mpt'
    | 'docm'
    | 'dotm'
    | 'wps'
    | 'wks'
    | 'wcm'
    | 'wdb'
    | 'wpl'
    | 'xps'
    | 'mseq'
    | 'mus'
    | 'msty'
    | 'taglet'
    | 'nlu'
    | 'ntf'
    | 'nitf'
    | 'nnd'
    | 'nns'
    | 'nnw'
    | '*ac'
    | 'ngdat'
    | 'n-gage'
    | 'rpst'
    | 'rpss'
    | 'edm'
    | 'edx'
    | 'ext'
    | 'odc'
    | 'otc'
    | 'odb'
    | 'odf'
    | 'odft'
    | 'odg'
    | 'otg'
    | 'odi'
    | 'oti'
    | 'odp'
    | 'otp'
    | 'ods'
    | 'ots'
    | 'odt'
    | 'odm'
    | 'ott'
    | 'oth'
    | 'xo'
    | 'dd2'
    | 'obgx'
    | 'oxt'
    | 'osm'
    | 'pptx'
    | 'sldx'
    | 'ppsx'
    | 'potx'
    | 'xlsx'
    | 'xltx'
    | 'docx'
    | 'dotx'
    | 'mgp'
    | 'dp'
    | 'esa'
    | 'pdb'
    | 'pqa'
    | 'oprc'
    | 'paw'
    | 'str'
    | 'ei6'
    | 'efif'
    | 'wg'
    | 'plf'
    | 'pbd'
    | 'box'
    | 'mgz'
    | 'qps'
    | 'ptid'
    | 'qxd'
    | 'qxt'
    | 'qwd'
    | 'qwt'
    | 'qxl'
    | 'qxb'
    | 'rar'
    | 'bed'
    | 'mxl'
    | 'musicxml'
    | 'cryptonote'
    | 'cod'
    | 'rm'
    | 'rmvb'
    | 'link66'
    | 'st'
    | 'see'
    | 'sema'
    | 'semd'
    | 'semf'
    | 'ifm'
    | 'itp'
    | 'iif'
    | 'ipk'
    | 'twd'
    | 'twds'
    | 'mmf'
    | 'teacher'
    | 'fo'
    | 'sdkm'
    | 'sdkd'
    | 'dxp'
    | 'sfs'
    | 'sdc'
    | 'sda'
    | 'sdd'
    | 'smf'
    | 'sdw'
    | 'vor'
    | 'sgl'
    | 'smzip'
    | 'sm'
    | 'wadl'
    | 'sxc'
    | 'stc'
    | 'sxd'
    | 'std'
    | 'sxi'
    | 'sti'
    | 'sxm'
    | 'sxw'
    | 'sxg'
    | 'stw'
    | 'sus'
    | 'susp'
    | 'svd'
    | 'sis'
    | 'sisx'
    | 'xsm'
    | 'bdm'
    | 'xdm'
    | 'ddf'
    | 'tao'
    | 'pcap'
    | 'cap'
    | 'dmp'
    | 'tmo'
    | 'tpt'
    | 'mxs'
    | 'tra'
    | 'ufd'
    | 'ufdl'
    | 'utz'
    | 'umj'
    | 'unityweb'
    | 'uoml'
    | 'vcx'
    | 'vsd'
    | 'vst'
    | 'vss'
    | 'vsw'
    | 'vis'
    | 'vsf'
    | 'wbxml'
    | 'wmlc'
    | 'wmlsc'
    | 'wtb'
    | 'nbp'
    | 'wpd'
    | 'wqd'
    | 'stf'
    | 'xar'
    | 'xfdl'
    | 'hvd'
    | 'hvs'
    | 'hvp'
    | 'osf'
    | 'osfpvg'
    | 'saf'
    | 'spf'
    | 'cmp'
    | 'zir'
    | 'zirz'
    | 'zaz'
    | '7z'
    | 'abw'
    | 'ace'
    | '*dmg'
    | 'arj'
    | 'aab'
    | 'x32'
    | 'u32'
    | 'vox'
    | 'aam'
    | 'aas'
    | 'bcpio'
    | '*bdoc'
    | 'torrent'
    | 'blb'
    | 'blorb'
    | 'bz'
    | 'bz2'
    | 'boz'
    | 'cbr'
    | 'cba'
    | 'cbt'
    | 'cbz'
    | 'cb7'
    | 'vcd'
    | 'cfs'
    | 'chat'
    | 'pgn'
    | 'crx'
    | 'cco'
    | 'nsc'
    | 'cpio'
    | 'csh'
    | '*deb'
    | 'udeb'
    | 'dgc'
    | 'dir'
    | 'dcr'
    | 'dxr'
    | 'cst'
    | 'cct'
    | 'cxt'
    | 'w3d'
    | 'fgd'
    | 'swa'
    | 'wad'
    | 'ncx'
    | 'dtb'
    | 'res'
    | 'dvi'
    | 'evy'
    | 'eva'
    | 'bdf'
    | 'gsf'
    | 'psf'
    | 'pcf'
    | 'snf'
    | 'pfa'
    | 'pfb'
    | 'pfm'
    | 'afm'
    | 'arc'
    | 'spl'
    | 'gca'
    | 'ulx'
    | 'gnumeric'
    | 'gramps'
    | 'gtar'
    | 'hdf'
    | 'php'
    | 'install'
    | '*iso'
    | '*key'
    | '*numbers'
    | '*pages'
    | 'jardiff'
    | 'jnlp'
    | 'kdbx'
    | 'latex'
    | 'luac'
    | 'lzh'
    | 'lha'
    | 'run'
    | 'mie'
    | 'prc'
    | 'mobi'
    | 'application'
    | 'lnk'
    | 'wmd'
    | 'wmz'
    | 'xbap'
    | 'mdb'
    | 'obd'
    | 'crd'
    | 'clp'
    | '*exe'
    | '*dll'
    | 'com'
    | 'bat'
    | '*msi'
    | 'mvb'
    | 'm13'
    | 'm14'
    | '*wmf'
    | '*wmz'
    | '*emf'
    | 'emz'
    | 'mny'
    | 'pub'
    | 'scd'
    | 'trm'
    | 'wri'
    | 'nc'
    | 'cdf'
    | 'pac'
    | 'nzb'
    | 'pl'
    | 'pm'
    | '*prc'
    | '*pdb'
    | 'p12'
    | 'pfx'
    | 'p7b'
    | 'spc'
    | 'p7r'
    | '*rar'
    | 'rpm'
    | 'ris'
    | 'sea'
    | 'sh'
    | 'shar'
    | 'swf'
    | 'xap'
    | 'sql'
    | 'sit'
    | 'sitx'
    | 'srt'
    | 'sv4cpio'
    | 'sv4crc'
    | 't3'
    | 'gam'
    | 'tar'
    | 'tcl'
    | 'tk'
    | 'tex'
    | 'tfm'
    | 'texinfo'
    | 'texi'
    | '*obj'
    | 'ustar'
    | 'hdd'
    | 'ova'
    | 'ovf'
    | 'vbox'
    | 'vbox-extpack'
    | 'vdi'
    | 'vhd'
    | 'vmdk'
    | 'src'
    | 'webapp'
    | 'der'
    | 'crt'
    | 'pem'
    | 'fig'
    | '*xlf'
    | 'xpi'
    | 'xz'
    | 'z1'
    | 'z2'
    | 'z3'
    | 'z4'
    | 'z5'
    | 'z6'
    | 'z7'
    | 'z8'
    | 'uva'
    | 'uvva'
    | 'eol'
    | 'dra'
    | 'dts'
    | 'dtshd'
    | 'lvp'
    | 'pya'
    | 'ecelp4800'
    | 'ecelp7470'
    | 'ecelp9600'
    | 'rip'
    | 'aac'
    | 'aif'
    | 'aiff'
    | 'aifc'
    | 'caf'
    | 'flac'
    | '*m4a'
    | 'mka'
    | 'm3u'
    | 'wax'
    | 'wma'
    | 'ram'
    | 'ra'
    | 'rmp'
    | '*ra'
    | 'cdx'
    | 'cif'
    | 'cmdf'
    | 'cml'
    | 'csml'
    | 'xyz'
    | 'btif'
    | 'pti'
    | 'psd'
    | 'azv'
    | 'uvi'
    | 'uvvi'
    | 'uvg'
    | 'uvvg'
    | 'djvu'
    | 'djv'
    | '*sub'
    | 'dwg'
    | 'dxf'
    | 'fbs'
    | 'fpx'
    | 'fst'
    | 'mmr'
    | 'rlc'
    | 'ico'
    | 'dds'
    | 'mdi'
    | 'wdp'
    | 'npx'
    | 'b16'
    | 'tap'
    | 'vtf'
    | 'wbmp'
    | 'xif'
    | 'pcx'
    | '3ds'
    | 'ras'
    | 'cmx'
    | 'fh'
    | 'fhc'
    | 'fh4'
    | 'fh5'
    | 'fh7'
    | '*ico'
    | 'jng'
    | 'sid'
    | '*bmp'
    | '*pcx'
    | 'pic'
    | 'pct'
    | 'pnm'
    | 'pbm'
    | 'pgm'
    | 'ppm'
    | 'rgb'
    | 'tga'
    | 'xbm'
    | 'xpm'
    | 'xwd'
    | 'wsc'
    | 'dae'
    | 'dwf'
    | 'gdl'
    | 'gtw'
    | 'mts'
    | 'ogex'
    | 'x_b'
    | 'x_t'
    | 'vds'
    | 'usdz'
    | 'bsp'
    | 'vtu'
    | 'dsc'
    | 'curl'
    | 'dcurl'
    | 'mcurl'
    | 'scurl'
    | 'sub'
    | 'fly'
    | 'flx'
    | 'gv'
    | '3dml'
    | 'spot'
    | 'jad'
    | 'wml'
    | 'wmls'
    | 's'
    | 'asm'
    | 'c'
    | 'cc'
    | 'cxx'
    | 'cpp'
    | 'h'
    | 'hh'
    | 'dic'
    | 'htc'
    | 'f'
    | 'for'
    | 'f77'
    | 'f90'
    | 'hbs'
    | 'java'
    | 'lua'
    | 'mkd'
    | 'nfo'
    | 'opml'
    | '*org'
    | 'p'
    | 'pas'
    | 'pde'
    | 'sass'
    | 'scss'
    | 'etx'
    | 'sfv'
    | 'ymp'
    | 'uu'
    | 'vcs'
    | 'vcf'
    | 'uvh'
    | 'uvvh'
    | 'uvm'
    | 'uvvm'
    | 'uvp'
    | 'uvvp'
    | 'uvs'
    | 'uvvs'
    | 'uvv'
    | 'uvvv'
    | 'dvb'
    | 'fvt'
    | 'mxu'
    | 'm4u'
    | 'pyv'
    | 'uvu'
    | 'uvvu'
    | 'viv'
    | 'f4v'
    | 'fli'
    | 'flv'
    | 'm4v'
    | 'mkv'
    | 'mk3d'
    | 'mks'
    | 'mng'
    | 'asf'
    | 'asx'
    | 'vob'
    | 'wm'
    | 'wmv'
    | 'wmx'
    | 'wvx'
    | 'avi'
    | 'movie'
    | 'smv'
    | 'ice'
    | 'mht'
    | null;
  source_value?: (string | number | boolean | Record<string, unknown> | unknown[]) | null;
}

export interface FileResult {
  data: Files;
  raw?: RawResponse[] | null;
}

export interface Files {
  /** Unique identifier */
  id?: string | null;
  /** Provider's unique identifier */
  remote_id?: string | null;
  /** The name associated with this file */
  name?: string | null;
  /** The description of the file */
  description?: string | null;
  /** The size of this file */
  size?: number | null;
  /** The url of the file */
  url?: string | null;
  /** The file format of the file */
  file_format?: FileFormatEnum | null;
  /** The path where the file is stored */
  path?: string | null;
  /** The user ID of owner of this file */
  owner_id?: string | null;
  /** List of supported export formats */
  export_formats?: string[] | null;
  /** Default download format */
  default_download_format?: string | null;
  /** Provider's unique identifier of the owner of this file */
  remote_owner_id?: string | null;
  /** The parent folder ID associated with this file */
  folder_id?: string | null;
  /** Provider's unique identifier of the parent folder associated with this file */
  remote_folder_id?: string | null;
  /** The parent drive ID associated with this file */
  drive_id?: string | null;
  /** Provider's unique identifier of the parent drive associated with this file */
  remote_drive_id?: string | null;
  /** The created date of the file */
  created_at?: string | null;
  /** The last updated date of the file */
  updated_at?: string | null;
  /** Whether the file has content */
  has_content?: (boolean | 'true' | 'false') | null;
  /** Whether the file has children */
  has_children?: (boolean | 'true' | 'false') | null;
  /** List of containing parent Folder IDs in descending order */
  all_parent_folder_ids?: string[] | null;
}

export interface FilesPaginated {
  next?: string | null;
  data: Files[];
  raw?: RawResponse[] | null;
}

export interface FolderResult {
  data: Folders;
  raw?: RawResponse[] | null;
}

export interface Folders {
  /** Unique identifier */
  id?: string | null;
  /** Provider's unique identifier */
  remote_id?: string | null;
  /** The name associated with this folder */
  name?: string | null;
  /** The description of the folder */
  description?: string | null;
  /** The size of this folder in bytes */
  size?: number | null;
  /** The url of the folder */
  url?: string | null;
  /** The path where the folder is stored */
  path?: string | null;
  /** The user ID of owner of this folder */
  owner_id?: string | null;
  /** Provider's unique identifier of the owner of this folder */
  remote_owner_id?: string | null;
  /** The parent folder ID associated with this folder */
  parent_folder_id?: string | null;
  /** Provider's unique identifier of the parent folder associated with this folder */
  remote_parent_folder_id?: string | null;
  /** The parent drive ID associated with this folder */
  drive_id?: string | null;
  /** Provider's unique identifier of the parent drive associated with this folder */
  remote_drive_id?: string | null;
  /** The created date of the folder */
  created_at?: string | null;
  /** The last updated date of the folder */
  updated_at?: string | null;
  /** Whether the folder has content */
  has_content?: (boolean | 'true' | 'false') | null;
  /** Whether the folder has children */
  has_children?: (boolean | 'true' | 'false') | null;
  /** Whether the folder is at the root level of the drive */
  is_root?: (boolean | 'true' | 'false') | null;
  /** List of containing parent Folder IDs in descending order */
  all_parent_folder_ids?: string[] | null;
}

export interface FoldersPaginated {
  next?: string | null;
  data: Folders[];
  raw?: RawResponse[] | null;
}

export interface ForbiddenResponse {
  /** HTTP status code */
  statusCode: number;
  /** Error message */
  message: string;
  /** Timestamp when the error occurred */
  timestamp: string;
}

export interface InternalServerErrorResponse {
  /** HTTP status code */
  statusCode: number;
  /** Error message */
  message: string;
  /** Timestamp when the error occurred */
  timestamp: string;
}

export interface NotFoundResponse {
  /** HTTP status code */
  statusCode: number;
  /** Error message */
  message: string;
  /** Timestamp when the error occurred */
  timestamp: string;
}

export interface NotImplementedResponse {
  /** HTTP status code */
  statusCode: number;
  /** Error message */
  message: string;
  /** Timestamp when the error occurred */
  timestamp: string;
}

export interface PreconditionFailedResponse {
  /** HTTP status code */
  statusCode: number;
  /** Error message */
  message: string;
  /** Timestamp when the error occurred */
  timestamp: string;
}

export interface ProviderError {
  /** HTTP status code of the provider error */
  status?: number | null;
  /** URL that caused the error */
  url?: string | null;
  /** Raw error response from the provider */
  raw?: Record<string, unknown> | null;
  /** Response headers */
  headers?: Record<string, unknown> | null;
}

export interface ProviderErrorApiModel {
  status?: number | null;
  url?: string | null;
  raw?: Record<string, unknown> | null;
  headers?: Record<string, unknown> | null;
}

export interface RawResponse {
  method: string;
  url: string;
  body?: (string | Record<string, unknown> | number[]) | null;
  response?: (Record<string, unknown> | unknown[] | string) | null;
}

export interface RequestTimedOutResponse {
  /** HTTP status code */
  statusCode: number;
  /** Error message */
  message: string;
  /** Timestamp when the error occurred */
  timestamp: string;
}

export interface TooManyRequestsResponse {
  /** HTTP status code */
  statusCode: number;
  /** Error message */
  message: string;
  /** Timestamp when the error occurred */
  timestamp: string;
}

export interface UnauthorizedResponse {
  /** HTTP status code */
  statusCode: number;
  /** Error message */
  message: string;
  /** Timestamp when the error occurred */
  timestamp: string;
}

export interface UnifiedError {
  /** HTTP status code */
  statusCode?: number | null;
  /** Error message */
  message?: string | null;
  /** Response headers */
  headers?: Record<string, unknown> | null;
}

export interface UnifiedUploadCategoryEnumApiModel {
  /** The category name for associating uploaded files. */
  value?: string | null;
  /** The provider specific category for associating uploaded files, if provided, the value will be ignored. */
  source_value?: string | null;
}

export interface UnifiedUploadRequestDto {
  /** The filename of the file to upload */
  name?: string | null;
  /** The file format of the file */
  file_format?: FileFormatEnum | null;
  /** The base64 encoded content of the file to upload */
  content?: string | null;
  /** The categoryId of the documents */
  category_id?: string | null;
  /** The path for the file to be uploaded to */
  path?: string | null;
  /** The category object for associating uploaded files. If both an ID and a name are provided, the ID takes precedence. */
  category?: UnifiedUploadCategoryEnumApiModel | null;
  /** The confidentiality level of the file to be uploaded */
  confidential?: ConfidentialEnumApiModel | null;
}

export interface UnifiedWarningApiModel {
  message?: string | null;
}

export interface UnprocessableEntityResponse {
  /** HTTP status code */
  statusCode: number;
  /** Error message */
  message: string;
  /** Timestamp when the error occurred */
  timestamp: string;
}

export interface WriteResultApiModel {
  statusCode?: number | null;
  message?: string | null;
  timestamp?: string | null;
  provider_errors?: ProviderErrorApiModel[] | null;
  unified_warnings?: UnifiedWarningApiModel[] | null;
}

// ============================================================
// Client Class
// ============================================================

export interface DocumentsDownloadFileParams {
  /** The session token */
  xStackoneApiSessionToken?: string;
  id: string;
  /** The format to download the file in */
  format?: string | null;
  /** The export format of the file */
  exportFormat?: string | null;
}

export interface DocumentsUploadFileParams {
  /** The session token */
  xStackoneApiSessionToken?: string;
  body: UnifiedUploadRequestDto;
}

export interface DocumentsListFilesParams {
  /** The session token */
  xStackoneApiSessionToken?: string;
  /** Indicates that the raw request result should be returned in addition to the mapped result (default value is false) */
  raw?: boolean | null;
  /** Query parameters that can be used to pass through parameters to the underlying provider request by surrounding them with 'proxy' key */
  proxy?: Record<string, unknown> | null;
  /** The comma separated list of fields that will be returned in the response (if empty, all fields are returned) */
  fields?: string | null;
  /** Documents Files Filter */
  filter?: {
    updated_after?: string | null;
    name?: string | null;
    content?: string | null;
    created_after?: string | null;
    drive_id?: string | null;
    folder_id?: string | null;
  } | null;
  /** The number of results per page (default value is 25) */
  pageSize?: string | null;
  /** The unified cursor */
  next?: string | null;
  /** Use to only include Files within the specified Folder. Required when requesting nested items */
  folderId?: string | null;
  /** When "true" and used with filter[folder_id], the response includes Files and Files within descendant Folders */
  nestedItems?: string | null;
  /** The comma separated list of fields that will be included in the response */
  include?: string | null;
}

export interface DocumentsGetFileParams {
  /** The session token */
  xStackoneApiSessionToken?: string;
  id: string;
  /** Indicates that the raw request result should be returned in addition to the mapped result (default value is false) */
  raw?: boolean | null;
  /** Query parameters that can be used to pass through parameters to the underlying provider request by surrounding them with 'proxy' key */
  proxy?: Record<string, unknown> | null;
  /** The comma separated list of fields that will be returned in the response (if empty, all fields are returned) */
  fields?: string | null;
  /** The comma separated list of fields that will be included in the response */
  include?: string | null;
}

export interface DocumentsListFoldersParams {
  /** Indicates that the raw request result should be returned in addition to the mapped result (default value is false) */
  raw?: boolean | null;
  /** Query parameters that can be used to pass through parameters to the underlying provider request by surrounding them with 'proxy' key */
  proxy?: Record<string, unknown> | null;
  /** The comma separated list of fields that will be returned in the response (if empty, all fields are returned) */
  fields?: string | null;
  /** Documents Folders Filter */
  filter?: {
    updated_after?: string | null;
    drive_id?: string | null;
    folder_id?: string | null;
  } | null;
  /** The number of results per page (default value is 25) */
  pageSize?: string | null;
  /** The unified cursor */
  next?: string | null;
  /** Use to only include Folders within the specified Folder. Required when requesting nested items */
  folderId?: string | null;
  /** When "true" and used with filter[folder_id], the response includes Folders and their descendant Folders */
  nestedItems?: string | null;
  /** The comma separated list of fields that will be included in the response */
  include?: string | null;
}

export interface DocumentsGetFolderParams {
  id: string;
  /** Indicates that the raw request result should be returned in addition to the mapped result (default value is false) */
  raw?: boolean | null;
  /** Query parameters that can be used to pass through parameters to the underlying provider request by surrounding them with 'proxy' key */
  proxy?: Record<string, unknown> | null;
  /** The comma separated list of fields that will be returned in the response (if empty, all fields are returned) */
  fields?: string | null;
  /** The comma separated list of fields that will be included in the response */
  include?: string | null;
}

export interface DocumentsListDrivesParams {
  /** Indicates that the raw request result should be returned in addition to the mapped result (default value is false) */
  raw?: boolean | null;
  /** Query parameters that can be used to pass through parameters to the underlying provider request by surrounding them with 'proxy' key */
  proxy?: Record<string, unknown> | null;
  /** The comma separated list of fields that will be returned in the response (if empty, all fields are returned) */
  fields?: string | null;
  /** Filter parameters that allow greater customisation of the list response */
  filter?: { updated_after?: string | null } | null;
  /** The number of results per page (default value is 25) */
  pageSize?: string | null;
  /** The unified cursor */
  next?: string | null;
}

export interface DocumentsGetDriveParams {
  id: string;
  /** Indicates that the raw request result should be returned in addition to the mapped result (default value is false) */
  raw?: boolean | null;
  /** Query parameters that can be used to pass through parameters to the underlying provider request by surrounding them with 'proxy' key */
  proxy?: Record<string, unknown> | null;
  /** The comma separated list of fields that will be returned in the response (if empty, all fields are returned) */
  fields?: string | null;
}

/**
 * Documents API Client
 * Auto-generated from OpenAPI specification
 */
export class DocumentsClient {
  private baseUrl: string;
  private headers: Record<string, string>;

  constructor(config: StackOneClientConfig) {
    this.baseUrl = config.baseUrl || 'https://api.stackone.com';
    const authToken = Buffer.from(`${config.apiKey}:`).toString('base64');
    this.headers = {
      Authorization: `Basic ${authToken}`,
      'x-account-id': config.accountId,
      ...config.headers,
    };
  }

  /**
   * Download File
   */
  async downloadFile(params: DocumentsDownloadFileParams): Promise<void> {
    let url = `${this.baseUrl}/unified/documents/files/${params.id}/download`;
    const queryParts: string[] = [];
    if (params.format !== undefined) {
      queryParts.push(`format=${encodeURIComponent(String(params.format))}`);
    }
    if (params.exportFormat !== undefined) {
      queryParts.push(`export_format=${encodeURIComponent(String(params.exportFormat))}`);
    }
    if (queryParts.length > 0) url += `?${queryParts.join('&')}`;
    const headers: Record<string, string> = {
      ...this.headers,
    };
    if (params.xStackoneApiSessionToken !== undefined) {
      headers['x-stackone-api-session-token'] = String(params.xStackoneApiSessionToken);
    }
    const options: RequestInit = {
      method: 'GET',
      headers,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return;
  }

  /**
   * Upload File
   */
  async uploadFile(params: DocumentsUploadFileParams): Promise<WriteResultApiModel> {
    const url = `${this.baseUrl}/unified/documents/files/upload`;
    const headers: Record<string, string> = {
      ...this.headers,
      'Content-Type': 'application/json',
    };
    if (params.xStackoneApiSessionToken !== undefined) {
      headers['x-stackone-api-session-token'] = String(params.xStackoneApiSessionToken);
    }
    const options: RequestInit = {
      method: 'POST',
      headers,
      body: params.body ? JSON.stringify(params.body) : undefined,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return response.json() as Promise<WriteResultApiModel>;
  }

  /**
   * List Files
   */
  async listFiles(params?: DocumentsListFilesParams): Promise<FilesPaginated> {
    let url = `${this.baseUrl}/unified/documents/files`;
    const queryParts: string[] = [];
    if (params?.raw !== undefined) {
      queryParts.push(`raw=${encodeURIComponent(String(params?.raw))}`);
    }
    if (params?.proxy !== undefined) {
      for (const [key, value] of Object.entries(params?.proxy as Record<string, unknown>)) {
        if (value !== undefined && value !== null) {
          queryParts.push(`proxy[${key}]=${encodeURIComponent(String(value))}`);
        }
      }
    }
    if (params?.fields !== undefined) {
      queryParts.push(`fields=${encodeURIComponent(String(params?.fields))}`);
    }
    if (params?.filter !== undefined) {
      queryParts.push(`filter=${encodeURIComponent(String(params?.filter))}`);
    }
    if (params?.pageSize !== undefined) {
      queryParts.push(`page_size=${encodeURIComponent(String(params?.pageSize))}`);
    }
    if (params?.next !== undefined) {
      queryParts.push(`next=${encodeURIComponent(String(params?.next))}`);
    }
    if (params?.folderId !== undefined) {
      queryParts.push(`folder_id=${encodeURIComponent(String(params?.folderId))}`);
    }
    if (params?.nestedItems !== undefined) {
      queryParts.push(`nested_items=${encodeURIComponent(String(params?.nestedItems))}`);
    }
    if (params?.include !== undefined) {
      queryParts.push(`include=${encodeURIComponent(String(params?.include))}`);
    }
    if (queryParts.length > 0) url += `?${queryParts.join('&')}`;
    const headers: Record<string, string> = {
      ...this.headers,
    };
    if (params?.xStackoneApiSessionToken !== undefined) {
      headers['x-stackone-api-session-token'] = String(params?.xStackoneApiSessionToken);
    }
    const options: RequestInit = {
      method: 'GET',
      headers,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return response.json() as Promise<FilesPaginated>;
  }

  /**
   * Get File
   */
  async getFile(params: DocumentsGetFileParams): Promise<FileResult> {
    let url = `${this.baseUrl}/unified/documents/files/${params.id}`;
    const queryParts: string[] = [];
    if (params.raw !== undefined) {
      queryParts.push(`raw=${encodeURIComponent(String(params.raw))}`);
    }
    if (params.proxy !== undefined) {
      for (const [key, value] of Object.entries(params.proxy as Record<string, unknown>)) {
        if (value !== undefined && value !== null) {
          queryParts.push(`proxy[${key}]=${encodeURIComponent(String(value))}`);
        }
      }
    }
    if (params.fields !== undefined) {
      queryParts.push(`fields=${encodeURIComponent(String(params.fields))}`);
    }
    if (params.include !== undefined) {
      queryParts.push(`include=${encodeURIComponent(String(params.include))}`);
    }
    if (queryParts.length > 0) url += `?${queryParts.join('&')}`;
    const headers: Record<string, string> = {
      ...this.headers,
    };
    if (params.xStackoneApiSessionToken !== undefined) {
      headers['x-stackone-api-session-token'] = String(params.xStackoneApiSessionToken);
    }
    const options: RequestInit = {
      method: 'GET',
      headers,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return response.json() as Promise<FileResult>;
  }

  /**
   * List Folders
   */
  async listFolders(params?: DocumentsListFoldersParams): Promise<FoldersPaginated> {
    let url = `${this.baseUrl}/unified/documents/folders`;
    const queryParts: string[] = [];
    if (params?.raw !== undefined) {
      queryParts.push(`raw=${encodeURIComponent(String(params?.raw))}`);
    }
    if (params?.proxy !== undefined) {
      for (const [key, value] of Object.entries(params?.proxy as Record<string, unknown>)) {
        if (value !== undefined && value !== null) {
          queryParts.push(`proxy[${key}]=${encodeURIComponent(String(value))}`);
        }
      }
    }
    if (params?.fields !== undefined) {
      queryParts.push(`fields=${encodeURIComponent(String(params?.fields))}`);
    }
    if (params?.filter !== undefined) {
      queryParts.push(`filter=${encodeURIComponent(String(params?.filter))}`);
    }
    if (params?.pageSize !== undefined) {
      queryParts.push(`page_size=${encodeURIComponent(String(params?.pageSize))}`);
    }
    if (params?.next !== undefined) {
      queryParts.push(`next=${encodeURIComponent(String(params?.next))}`);
    }
    if (params?.folderId !== undefined) {
      queryParts.push(`folder_id=${encodeURIComponent(String(params?.folderId))}`);
    }
    if (params?.nestedItems !== undefined) {
      queryParts.push(`nested_items=${encodeURIComponent(String(params?.nestedItems))}`);
    }
    if (params?.include !== undefined) {
      queryParts.push(`include=${encodeURIComponent(String(params?.include))}`);
    }
    if (queryParts.length > 0) url += `?${queryParts.join('&')}`;
    const headers: Record<string, string> = {
      ...this.headers,
    };
    const options: RequestInit = {
      method: 'GET',
      headers,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return response.json() as Promise<FoldersPaginated>;
  }

  /**
   * Get Folder
   */
  async getFolder(params: DocumentsGetFolderParams): Promise<FolderResult> {
    let url = `${this.baseUrl}/unified/documents/folders/${params.id}`;
    const queryParts: string[] = [];
    if (params.raw !== undefined) {
      queryParts.push(`raw=${encodeURIComponent(String(params.raw))}`);
    }
    if (params.proxy !== undefined) {
      for (const [key, value] of Object.entries(params.proxy as Record<string, unknown>)) {
        if (value !== undefined && value !== null) {
          queryParts.push(`proxy[${key}]=${encodeURIComponent(String(value))}`);
        }
      }
    }
    if (params.fields !== undefined) {
      queryParts.push(`fields=${encodeURIComponent(String(params.fields))}`);
    }
    if (params.include !== undefined) {
      queryParts.push(`include=${encodeURIComponent(String(params.include))}`);
    }
    if (queryParts.length > 0) url += `?${queryParts.join('&')}`;
    const headers: Record<string, string> = {
      ...this.headers,
    };
    const options: RequestInit = {
      method: 'GET',
      headers,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return response.json() as Promise<FolderResult>;
  }

  /**
   * List Drives
   */
  async listDrives(params?: DocumentsListDrivesParams): Promise<DrivesPaginated> {
    let url = `${this.baseUrl}/unified/documents/drives`;
    const queryParts: string[] = [];
    if (params?.raw !== undefined) {
      queryParts.push(`raw=${encodeURIComponent(String(params?.raw))}`);
    }
    if (params?.proxy !== undefined) {
      for (const [key, value] of Object.entries(params?.proxy as Record<string, unknown>)) {
        if (value !== undefined && value !== null) {
          queryParts.push(`proxy[${key}]=${encodeURIComponent(String(value))}`);
        }
      }
    }
    if (params?.fields !== undefined) {
      queryParts.push(`fields=${encodeURIComponent(String(params?.fields))}`);
    }
    if (params?.filter !== undefined) {
      queryParts.push(`filter=${encodeURIComponent(String(params?.filter))}`);
    }
    if (params?.pageSize !== undefined) {
      queryParts.push(`page_size=${encodeURIComponent(String(params?.pageSize))}`);
    }
    if (params?.next !== undefined) {
      queryParts.push(`next=${encodeURIComponent(String(params?.next))}`);
    }
    if (queryParts.length > 0) url += `?${queryParts.join('&')}`;
    const headers: Record<string, string> = {
      ...this.headers,
    };
    const options: RequestInit = {
      method: 'GET',
      headers,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return response.json() as Promise<DrivesPaginated>;
  }

  /**
   * Get Drive
   */
  async getDrive(params: DocumentsGetDriveParams): Promise<DriveResult> {
    let url = `${this.baseUrl}/unified/documents/drives/${params.id}`;
    const queryParts: string[] = [];
    if (params.raw !== undefined) {
      queryParts.push(`raw=${encodeURIComponent(String(params.raw))}`);
    }
    if (params.proxy !== undefined) {
      for (const [key, value] of Object.entries(params.proxy as Record<string, unknown>)) {
        if (value !== undefined && value !== null) {
          queryParts.push(`proxy[${key}]=${encodeURIComponent(String(value))}`);
        }
      }
    }
    if (params.fields !== undefined) {
      queryParts.push(`fields=${encodeURIComponent(String(params.fields))}`);
    }
    if (queryParts.length > 0) url += `?${queryParts.join('&')}`;
    const headers: Record<string, string> = {
      ...this.headers,
    };
    const options: RequestInit = {
      method: 'GET',
      headers,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return response.json() as Promise<DriveResult>;
  }
}
