// Auto-generated index file
// DO NOT EDIT THIS FILE DIRECTLY

export * from './types';

// Export client classes from each module
// Types are available via each module namespace to avoid conflicts
export { StackoneClient } from './stackone';
export { CrmClient } from './crm';
export { AtsClient } from './ats';
export { HrisClient } from './hris';
export { DocumentsClient } from './documents';
export { MarketingClient } from './marketing';
export { TicketingClient } from './ticketing';
export { ScreeningClient } from './screening';
export { MessagingClient } from './messaging';
export { IamClient } from './iam';
export { LmsClient } from './lms';

// Re-export namespaces for accessing types
export * as stackone from './stackone';
export * as crm from './crm';
export * as ats from './ats';
export * as hris from './hris';
export * as documents from './documents';
export * as marketing from './marketing';
export * as ticketing from './ticketing';
export * as screening from './screening';
export * as messaging from './messaging';
export * as iam from './iam';
export * as lms from './lms';
