// Auto-generated TypeScript SDK from OpenAPI specification
// DO NOT EDIT THIS FILE DIRECTLY

import type { StackOneClientConfig } from './types';

// ============================================================
// Type Definitions
// ============================================================

// Auto-generated TypeScript interfaces from OpenAPI schemas
// DO NOT EDIT THIS FILE DIRECTLY

export interface BadGatewayResponse {
  /** HTTP status code */
  statusCode: number;
  /** Error message */
  message: string;
  /** Timestamp when the error occurred */
  timestamp: string;
}

export interface BadRequestResponse {
  /** HTTP status code */
  statusCode: number;
  /** Error message */
  message: string;
  /** Timestamp when the error occurred */
  timestamp: string;
  /** Error details */
  data?: UnifiedError | null;
  /** List of provider-specific errors */
  provider_errors?: ProviderError[] | null;
}

export interface Campaign {
  /** Unique identifier */
  id?: string | null;
  /** Provider's unique identifier */
  remote_id?: string | null;
  name?: string | null;
  /** The created_at date */
  created_at?: string | null;
  /** The updated_at date */
  updated_at?: string | null;
  description?: string | null;
  /** The schedule type */
  schedule_type?: ScheduleTypeEnum | null;
  /** Status of the Campaign */
  status?: StatusEnum | null;
  archived?: (boolean | 'true' | 'false') | null;
  draft?: (boolean | 'true' | 'false') | null;
  /** channels of the Campaign */
  channels?: ChannelsEnum[] | null;
  /** The first_sent_at date */
  first_sent_at?: string | null;
  /** The last_sent_at date */
  last_sent_at?: string | null;
  tags?: string[] | null;
  messages?: Message[] | null;
}

export interface CampaignResult {
  data: Campaign;
  raw?: RawResponse[] | null;
}

export interface CampaignsPaginated {
  next_page?: string | null;
  next?: string | null;
  data: Campaign[];
  raw?: RawResponse[] | null;
}

export interface ChannelsEnum {
  /** The Channels of the campaign. */
  value?:
    | 'email'
    | 'sms'
    | 'web_push'
    | 'ios_push'
    | 'android_push'
    | 'unknown'
    | 'unmapped_value'
    | null;
  /** The source value of the Channels. */
  source_value?: (string | number | boolean | Record<string, unknown> | unknown[]) | null;
}

export interface ConflictResponse {
  /** HTTP status code */
  statusCode: number;
  /** Error message */
  message: string;
  /** Timestamp when the error occurred */
  timestamp: string;
}

export interface ContentBlock {
  /** Unique identifier */
  id?: string | null;
  /** Provider's unique identifier */
  remote_id?: string | null;
  name?: string | null;
  tags?: string[] | null;
  content?: string | null;
  /** Stackone enum identifying the type of content block. */
  type?: ContentBlockTypeEnumApiModel | null;
  /** Stackone enum identifying the status of content block. */
  status?: ContentBlockStatusEnumApiModel | null;
  /** Date of creation */
  created_at?: string | null;
  /** Date of last update */
  updated_at?: string | null;
}

export interface ContentBlockResult {
  data: ContentBlock;
  raw?: RawResponse[] | null;
}

export interface ContentBlocksPaginated {
  next_page?: string | null;
  next?: string | null;
  data: ContentBlock[];
  raw?: RawResponse[] | null;
}

export interface ContentBlockStatusEnumApiModel {
  /** The Status of the content blocks. */
  value?: 'draft' | 'live' | 'archived' | 'unmapped_value' | null;
  /** The source value of the status. */
  source_value?: (string | number | boolean | Record<string, unknown> | unknown[]) | null;
}

export interface ContentBlockTypeEnumApiModel {
  /** The type of the content blocks. */
  value?: 'text' | 'html' | 'image' | 'code-snippet' | 'unmapped_value' | null;
  /** The source value of the type. */
  source_value?: (string | number | boolean | Record<string, unknown> | unknown[]) | null;
}

export interface CreateMessage {
  /** Unique identifier */
  id?: string | null;
  name?: string | null;
  /** Stackone enum identifying the type of message associated with the content. */
  message_type?: MessageTypeEnum | null;
  message_content?: (SmsMessageContents | EmailMessageContents | PushMessageContents) | null;
}

export interface CreateResult {
  statusCode: number;
  message: string;
  timestamp: string;
  data: CreateResultDataApiModel;
}

export interface CreateResultDataApiModel {
  /** Unique identifier */
  id?: string | null;
  /** Provider's unique identifier */
  remote_id?: string | null;
}

export interface EmailMessageContents {
  subject?: string | null;
  body?: string | null;
  from?: string | null;
  'reply-to'?: string | null;
  preheader?: string | null;
}

export interface EmailMessages {
  /** Unique identifier */
  id?: string | null;
  /** Provider's unique identifier */
  remote_id?: string | null;
  name?: string | null;
  message_type?: MessageTypeEnum | null;
  message_content?: EmailMessageContents | null;
}

export interface EmailTemplate {
  /** Unique identifier */
  id?: string | null;
  /** Provider's unique identifier */
  remote_id?: string | null;
  name?: string | null;
  tags?: string[] | null;
  /** Date of creation */
  created_at?: string | null;
  /** Date of last update */
  updated_at?: string | null;
  messages?: EmailMessages[] | null;
}

export interface EmailTemplateResult {
  data: EmailTemplate;
  raw?: RawResponse[] | null;
}

export interface EmailTemplatesPaginated {
  next_page?: string | null;
  next?: string | null;
  data: EmailTemplate[];
  raw?: RawResponse[] | null;
}

export interface ForbiddenResponse {
  /** HTTP status code */
  statusCode: number;
  /** Error message */
  message: string;
  /** Timestamp when the error occurred */
  timestamp: string;
}

export interface InAppMessageContents {
  body?: string | null;
}

export interface InAppMessages {
  /** Unique identifier */
  id?: string | null;
  /** Provider's unique identifier */
  remote_id?: string | null;
  name?: string | null;
  message_type?: MessageTypeEnum | null;
  message_content?: InAppMessageContents | null;
}

export interface InAppTemplate {
  /** Unique identifier */
  id?: string | null;
  /** Provider's unique identifier */
  remote_id?: string | null;
  name?: string | null;
  tags?: string[] | null;
  /** Date of creation */
  created_at?: string | null;
  /** Date of last update */
  updated_at?: string | null;
  messages?: InAppMessages[] | null;
}

export interface InAppTemplateResult {
  data: InAppTemplate;
  raw?: RawResponse[] | null;
}

export interface InAppTemplatesPaginated {
  next_page?: string | null;
  next?: string | null;
  data: InAppTemplate[];
  raw?: RawResponse[] | null;
}

export interface InternalServerErrorResponse {
  /** HTTP status code */
  statusCode: number;
  /** Error message */
  message: string;
  /** Timestamp when the error occurred */
  timestamp: string;
}

export interface MarketingCreateContentBlocksRequestDto {
  name?: string | null;
  tags?: string[] | null;
  content?: string | null;
  /** Stackone enum identifying the type of content block. */
  type?: ContentBlockTypeEnumApiModel | null;
  /** Value to pass through to the provider */
  passthrough?: Record<string, unknown> | null;
}

export interface MarketingCreateEmailTemplateRequestDto {
  name?: string | null;
  tags?: string[] | null;
  messages?: EmailMessages[] | null;
  /** Value to pass through to the provider */
  passthrough?: Record<string, unknown> | null;
}

export interface MarketingCreateInAppTemplateRequestDto {
  name?: string | null;
  tags?: string[] | null;
  messages?: InAppMessages[] | null;
  /** Value to pass through to the provider */
  passthrough?: Record<string, unknown> | null;
}

export interface MarketingCreatePushTemplateRequestDto {
  name?: string | null;
  tags?: string[] | null;
  messages?: PushMessages[] | null;
  /** Value to pass through to the provider */
  passthrough?: Record<string, unknown> | null;
}

export interface MarketingCreateSmsTemplateRequestDto {
  name?: string | null;
  tags?: string[] | null;
  messages?: SmsMessages[] | null;
  /** Value to pass through to the provider */
  passthrough?: Record<string, unknown> | null;
}

export interface MarketingCreateTemplateRequestDto {
  messages?: CreateMessage[] | null;
  name?: string | null;
  tags?: string[] | null;
  /** Value to pass through to the provider */
  passthrough?: Record<string, unknown> | null;
}

export interface Message {
  /** Unique identifier */
  id?: string | null;
  /** Provider's unique identifier */
  remote_id?: string | null;
  name?: string | null;
  /** Stackone enum identifying the type of message associated with the content. */
  message_type?: MessageTypeEnum | null;
  message_content?: (SmsMessageContents | EmailMessageContents | PushMessageContents) | null;
}

export interface MessageTypeEnum {
  /** The unified message type. */
  value?:
    | 'email'
    | 'sms'
    | 'push'
    | 'web_push'
    | 'ios_push'
    | 'android_push'
    | 'app_push'
    | 'omni_channel'
    | 'content_block'
    | 'in_app'
    | 'unknown'
    | 'unmapped_value'
    | null;
  /** The original value from the provider used to derive the unified message type. */
  source_value?: (string | number | boolean | Record<string, unknown> | unknown[]) | null;
}

export interface NotFoundResponse {
  /** HTTP status code */
  statusCode: number;
  /** Error message */
  message: string;
  /** Timestamp when the error occurred */
  timestamp: string;
}

export interface NotImplementedResponse {
  /** HTTP status code */
  statusCode: number;
  /** Error message */
  message: string;
  /** Timestamp when the error occurred */
  timestamp: string;
}

export interface PreconditionFailedResponse {
  /** HTTP status code */
  statusCode: number;
  /** Error message */
  message: string;
  /** Timestamp when the error occurred */
  timestamp: string;
}

export interface ProviderError {
  /** HTTP status code of the provider error */
  status?: number | null;
  /** URL that caused the error */
  url?: string | null;
  /** Raw error response from the provider */
  raw?: Record<string, unknown> | null;
  /** Response headers */
  headers?: Record<string, unknown> | null;
}

export interface PushMessageContents {
  title?: string | null;
  subtitle?: string | null;
  body?: string | null;
}

export interface PushMessages {
  /** Unique identifier */
  id?: string | null;
  /** Provider's unique identifier */
  remote_id?: string | null;
  name?: string | null;
  message_type?: MessageTypeEnum | null;
  message_content?: PushMessageContents | null;
}

export interface PushTemplate {
  /** Unique identifier */
  id?: string | null;
  /** Provider's unique identifier */
  remote_id?: string | null;
  name?: string | null;
  tags?: string[] | null;
  /** Date of creation */
  created_at?: string | null;
  /** Date of last update */
  updated_at?: string | null;
  messages?: PushMessages[] | null;
}

export interface PushTemplateResult {
  data: PushTemplate;
  raw?: RawResponse[] | null;
}

export interface PushTemplatesPaginated {
  next_page?: string | null;
  next?: string | null;
  data: PushTemplate[];
  raw?: RawResponse[] | null;
}

export interface RawResponse {
  method: string;
  url: string;
  body?: (string | Record<string, unknown> | number[]) | null;
  response?: (Record<string, unknown> | unknown[] | string) | null;
}

export interface RequestTimedOutResponse {
  /** HTTP status code */
  statusCode: number;
  /** Error message */
  message: string;
  /** Timestamp when the error occurred */
  timestamp: string;
}

export interface ScheduleTypeEnum {
  /** The schedule type of the campaign. */
  value?:
    | 'immediate'
    | 'scheduled'
    | 'recurring'
    | 'custom'
    | 'triggered'
    | 'unmapped_value'
    | null;
  /** The source value of the schedule type. */
  source_value?: (string | number | boolean | Record<string, unknown> | unknown[]) | null;
}

export interface SmsMessageContents {
  body?: string | null;
  from?: string | null;
}

export interface SmsMessages {
  /** Unique identifier */
  id?: string | null;
  /** Provider's unique identifier */
  remote_id?: string | null;
  name?: string | null;
  message_type?: MessageTypeEnum | null;
  message_content?: SmsMessageContents | null;
}

export interface SmsTemplate {
  /** Unique identifier */
  id?: string | null;
  /** Provider's unique identifier */
  remote_id?: string | null;
  name?: string | null;
  tags?: string[] | null;
  /** Date of creation */
  created_at?: string | null;
  /** Date of last update */
  updated_at?: string | null;
  messages?: SmsMessages[] | null;
}

export interface SmsTemplateResult {
  data: SmsTemplate;
  raw?: RawResponse[] | null;
}

export interface SmsTemplatesPaginated {
  next_page?: string | null;
  next?: string | null;
  data: SmsTemplate[];
  raw?: RawResponse[] | null;
}

export interface StatusEnum {
  /** The Status of the campaign. */
  value?: 'draft' | 'archived' | 'live' | 'unmapped_value' | null;
  /** The source value of the Status. */
  source_value?: (string | number | boolean | Record<string, unknown> | unknown[]) | null;
}

export interface Template {
  /** Unique identifier */
  id?: string | null;
  /** Provider's unique identifier */
  remote_id?: string | null;
  name?: string | null;
  tags?: string[] | null;
  /** Date of creation */
  created_at?: string | null;
  /** Date of last update */
  updated_at?: string | null;
}

export interface TemplateResult {
  data: Template;
  raw?: RawResponse[] | null;
}

export interface TemplatesPaginated {
  next_page?: string | null;
  next?: string | null;
  data: Template[];
  raw?: RawResponse[] | null;
}

export interface TooManyRequestsResponse {
  /** HTTP status code */
  statusCode: number;
  /** Error message */
  message: string;
  /** Timestamp when the error occurred */
  timestamp: string;
}

export interface UnauthorizedResponse {
  /** HTTP status code */
  statusCode: number;
  /** Error message */
  message: string;
  /** Timestamp when the error occurred */
  timestamp: string;
}

export interface UnifiedError {
  /** HTTP status code */
  statusCode?: number | null;
  /** Error message */
  message?: string | null;
  /** Response headers */
  headers?: Record<string, unknown> | null;
}

export interface UnprocessableEntityResponse {
  /** HTTP status code */
  statusCode: number;
  /** Error message */
  message: string;
  /** Timestamp when the error occurred */
  timestamp: string;
}

// ============================================================
// Client Class
// ============================================================

export interface MarketingListEmailTemplatesParams {
  /** Indicates that the raw request result should be returned in addition to the mapped result (default value is false) */
  raw?: boolean | null;
  /** Query parameters that can be used to pass through parameters to the underlying provider request by surrounding them with 'proxy' key */
  proxy?: Record<string, unknown> | null;
  /** The comma separated list of fields that will be returned in the response (if empty, all fields are returned) */
  fields?: string | null;
  /** Filter parameters that allow greater customisation of the list response */
  filter?: { updated_after?: string | null } | null;
  /** The number of results per page (default value is 25) */
  pageSize?: string | null;
  /** The unified cursor */
  next?: string | null;
}

export interface MarketingCreateEmailTemplateParams {
  body: MarketingCreateEmailTemplateRequestDto;
}

export interface MarketingGetEmailTemplateParams {
  id: string;
  /** Indicates that the raw request result should be returned in addition to the mapped result (default value is false) */
  raw?: boolean | null;
  /** Query parameters that can be used to pass through parameters to the underlying provider request by surrounding them with 'proxy' key */
  proxy?: Record<string, unknown> | null;
  /** The comma separated list of fields that will be returned in the response (if empty, all fields are returned) */
  fields?: string | null;
}

export interface MarketingUpdateEmailTemplateParams {
  id: string;
  body: MarketingCreateEmailTemplateRequestDto;
}

export interface MarketingListInAppTemplatesParams {
  /** Indicates that the raw request result should be returned in addition to the mapped result (default value is false) */
  raw?: boolean | null;
  /** Query parameters that can be used to pass through parameters to the underlying provider request by surrounding them with 'proxy' key */
  proxy?: Record<string, unknown> | null;
  /** The comma separated list of fields that will be returned in the response (if empty, all fields are returned) */
  fields?: string | null;
  /** Filter parameters that allow greater customisation of the list response */
  filter?: { updated_after?: string | null } | null;
  /** The number of results per page (default value is 25) */
  pageSize?: string | null;
  /** The unified cursor */
  next?: string | null;
}

export interface MarketingCreateInAppTemplateParams {
  body: MarketingCreateInAppTemplateRequestDto;
}

export interface MarketingGetInAppTemplateParams {
  id: string;
  /** Indicates that the raw request result should be returned in addition to the mapped result (default value is false) */
  raw?: boolean | null;
  /** Query parameters that can be used to pass through parameters to the underlying provider request by surrounding them with 'proxy' key */
  proxy?: Record<string, unknown> | null;
  /** The comma separated list of fields that will be returned in the response (if empty, all fields are returned) */
  fields?: string | null;
}

export interface MarketingUpdateInAppTemplateParams {
  id: string;
  body: MarketingCreateInAppTemplateRequestDto;
}

export interface MarketingListSmsTemplatesParams {
  /** Indicates that the raw request result should be returned in addition to the mapped result (default value is false) */
  raw?: boolean | null;
  /** Query parameters that can be used to pass through parameters to the underlying provider request by surrounding them with 'proxy' key */
  proxy?: Record<string, unknown> | null;
  /** The comma separated list of fields that will be returned in the response (if empty, all fields are returned) */
  fields?: string | null;
  /** Filter parameters that allow greater customisation of the list response */
  filter?: { updated_after?: string | null } | null;
  /** The number of results per page (default value is 25) */
  pageSize?: string | null;
  /** The unified cursor */
  next?: string | null;
}

export interface MarketingCreateSmsTemplateParams {
  body: MarketingCreateSmsTemplateRequestDto;
}

export interface MarketingGetSmsTemplateParams {
  id: string;
  /** Indicates that the raw request result should be returned in addition to the mapped result (default value is false) */
  raw?: boolean | null;
  /** Query parameters that can be used to pass through parameters to the underlying provider request by surrounding them with 'proxy' key */
  proxy?: Record<string, unknown> | null;
  /** The comma separated list of fields that will be returned in the response (if empty, all fields are returned) */
  fields?: string | null;
}

export interface MarketingUpdateSmsTemplateParams {
  id: string;
  body: MarketingCreateSmsTemplateRequestDto;
}

export interface MarketingListPushTemplatesParams {
  /** Indicates that the raw request result should be returned in addition to the mapped result (default value is false) */
  raw?: boolean | null;
  /** Query parameters that can be used to pass through parameters to the underlying provider request by surrounding them with 'proxy' key */
  proxy?: Record<string, unknown> | null;
  /** The comma separated list of fields that will be returned in the response (if empty, all fields are returned) */
  fields?: string | null;
  /** Filter parameters that allow greater customisation of the list response */
  filter?: { updated_after?: string | null } | null;
  /** The number of results per page (default value is 25) */
  pageSize?: string | null;
  /** The unified cursor */
  next?: string | null;
}

export interface MarketingCreatePushTemplateParams {
  body: MarketingCreatePushTemplateRequestDto;
}

export interface MarketingGetPushTemplateParams {
  id: string;
  /** Indicates that the raw request result should be returned in addition to the mapped result (default value is false) */
  raw?: boolean | null;
  /** Query parameters that can be used to pass through parameters to the underlying provider request by surrounding them with 'proxy' key */
  proxy?: Record<string, unknown> | null;
  /** The comma separated list of fields that will be returned in the response (if empty, all fields are returned) */
  fields?: string | null;
}

export interface MarketingUpdatePushTemplateParams {
  id: string;
  body: MarketingCreatePushTemplateRequestDto;
}

export interface MarketingListCampaignsParams {
  /** Indicates that the raw request result should be returned in addition to the mapped result (default value is false) */
  raw?: boolean | null;
  /** Query parameters that can be used to pass through parameters to the underlying provider request by surrounding them with 'proxy' key */
  proxy?: Record<string, unknown> | null;
  /** The comma separated list of fields that will be returned in the response (if empty, all fields are returned) */
  fields?: string | null;
  /** Filter parameters that allow greater customisation of the list response */
  filter?: { updated_after?: string | null } | null;
  /** The number of results per page (default value is 25) */
  pageSize?: string | null;
  /** The unified cursor */
  next?: string | null;
}

export interface MarketingGetCampaignParams {
  id: string;
  /** Indicates that the raw request result should be returned in addition to the mapped result (default value is false) */
  raw?: boolean | null;
  /** Query parameters that can be used to pass through parameters to the underlying provider request by surrounding them with 'proxy' key */
  proxy?: Record<string, unknown> | null;
  /** The comma separated list of fields that will be returned in the response (if empty, all fields are returned) */
  fields?: string | null;
}

export interface MarketingListContentBlocksParams {
  /** Indicates that the raw request result should be returned in addition to the mapped result (default value is false) */
  raw?: boolean | null;
  /** Query parameters that can be used to pass through parameters to the underlying provider request by surrounding them with 'proxy' key */
  proxy?: Record<string, unknown> | null;
  /** The comma separated list of fields that will be returned in the response (if empty, all fields are returned) */
  fields?: string | null;
  /** Filter parameters that allow greater customisation of the list response */
  filter?: { updated_after?: string | null } | null;
  /** The number of results per page (default value is 25) */
  pageSize?: string | null;
  /** The unified cursor */
  next?: string | null;
}

export interface MarketingCreateContentBlockParams {
  body: MarketingCreateContentBlocksRequestDto;
}

export interface MarketingGetContentBlockParams {
  id: string;
  /** Indicates that the raw request result should be returned in addition to the mapped result (default value is false) */
  raw?: boolean | null;
  /** Query parameters that can be used to pass through parameters to the underlying provider request by surrounding them with 'proxy' key */
  proxy?: Record<string, unknown> | null;
  /** The comma separated list of fields that will be returned in the response (if empty, all fields are returned) */
  fields?: string | null;
}

export interface MarketingUpdateContentBlockParams {
  id: string;
  body: MarketingCreateContentBlocksRequestDto;
}

/**
 * Marketing API Client
 * Auto-generated from OpenAPI specification
 */
export class MarketingClient {
  private baseUrl: string;
  private headers: Record<string, string>;

  constructor(config: StackOneClientConfig) {
    this.baseUrl = config.baseUrl || 'https://api.stackone.com';
    const authToken = Buffer.from(`${config.apiKey}:`).toString('base64');
    this.headers = {
      Authorization: `Basic ${authToken}`,
      'x-account-id': config.accountId,
      ...config.headers,
    };
  }

  /**
   * List Email Templates
   */
  async listEmailTemplates(
    params?: MarketingListEmailTemplatesParams
  ): Promise<EmailTemplatesPaginated> {
    let url = `${this.baseUrl}/unified/marketing/templates/email`;
    const queryParts: string[] = [];
    if (params?.raw !== undefined) {
      queryParts.push(`raw=${encodeURIComponent(String(params?.raw))}`);
    }
    if (params?.proxy !== undefined) {
      for (const [key, value] of Object.entries(params?.proxy as Record<string, unknown>)) {
        if (value !== undefined && value !== null) {
          queryParts.push(`proxy[${key}]=${encodeURIComponent(String(value))}`);
        }
      }
    }
    if (params?.fields !== undefined) {
      queryParts.push(`fields=${encodeURIComponent(String(params?.fields))}`);
    }
    if (params?.filter !== undefined) {
      queryParts.push(`filter=${encodeURIComponent(String(params?.filter))}`);
    }
    if (params?.pageSize !== undefined) {
      queryParts.push(`page_size=${encodeURIComponent(String(params?.pageSize))}`);
    }
    if (params?.next !== undefined) {
      queryParts.push(`next=${encodeURIComponent(String(params?.next))}`);
    }
    if (queryParts.length > 0) url += `?${queryParts.join('&')}`;
    const headers: Record<string, string> = {
      ...this.headers,
    };
    const options: RequestInit = {
      method: 'GET',
      headers,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return response.json() as Promise<EmailTemplatesPaginated>;
  }

  /**
   * Create Email Templates
   */
  async createEmailTemplate(params: MarketingCreateEmailTemplateParams): Promise<CreateResult> {
    const url = `${this.baseUrl}/unified/marketing/templates/email`;
    const headers: Record<string, string> = {
      ...this.headers,
      'Content-Type': 'application/json',
    };
    const options: RequestInit = {
      method: 'POST',
      headers,
      body: params.body ? JSON.stringify(params.body) : undefined,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return response.json() as Promise<CreateResult>;
  }

  /**
   * Get Email Templates
   */
  async getEmailTemplate(params: MarketingGetEmailTemplateParams): Promise<EmailTemplateResult> {
    let url = `${this.baseUrl}/unified/marketing/templates/email/${params.id}`;
    const queryParts: string[] = [];
    if (params.raw !== undefined) {
      queryParts.push(`raw=${encodeURIComponent(String(params.raw))}`);
    }
    if (params.proxy !== undefined) {
      for (const [key, value] of Object.entries(params.proxy as Record<string, unknown>)) {
        if (value !== undefined && value !== null) {
          queryParts.push(`proxy[${key}]=${encodeURIComponent(String(value))}`);
        }
      }
    }
    if (params.fields !== undefined) {
      queryParts.push(`fields=${encodeURIComponent(String(params.fields))}`);
    }
    if (queryParts.length > 0) url += `?${queryParts.join('&')}`;
    const headers: Record<string, string> = {
      ...this.headers,
    };
    const options: RequestInit = {
      method: 'GET',
      headers,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return response.json() as Promise<EmailTemplateResult>;
  }

  /**
   * Update Email Templates
   */
  async updateEmailTemplate(params: MarketingUpdateEmailTemplateParams): Promise<CreateResult> {
    const url = `${this.baseUrl}/unified/marketing/templates/email/${params.id}`;
    const headers: Record<string, string> = {
      ...this.headers,
      'Content-Type': 'application/json',
    };
    const options: RequestInit = {
      method: 'PATCH',
      headers,
      body: params.body ? JSON.stringify(params.body) : undefined,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return response.json() as Promise<CreateResult>;
  }

  /**
   * List In-App Templates
   */
  async listInAppTemplates(
    params?: MarketingListInAppTemplatesParams
  ): Promise<InAppTemplatesPaginated> {
    let url = `${this.baseUrl}/unified/marketing/templates/in_app`;
    const queryParts: string[] = [];
    if (params?.raw !== undefined) {
      queryParts.push(`raw=${encodeURIComponent(String(params?.raw))}`);
    }
    if (params?.proxy !== undefined) {
      for (const [key, value] of Object.entries(params?.proxy as Record<string, unknown>)) {
        if (value !== undefined && value !== null) {
          queryParts.push(`proxy[${key}]=${encodeURIComponent(String(value))}`);
        }
      }
    }
    if (params?.fields !== undefined) {
      queryParts.push(`fields=${encodeURIComponent(String(params?.fields))}`);
    }
    if (params?.filter !== undefined) {
      queryParts.push(`filter=${encodeURIComponent(String(params?.filter))}`);
    }
    if (params?.pageSize !== undefined) {
      queryParts.push(`page_size=${encodeURIComponent(String(params?.pageSize))}`);
    }
    if (params?.next !== undefined) {
      queryParts.push(`next=${encodeURIComponent(String(params?.next))}`);
    }
    if (queryParts.length > 0) url += `?${queryParts.join('&')}`;
    const headers: Record<string, string> = {
      ...this.headers,
    };
    const options: RequestInit = {
      method: 'GET',
      headers,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return response.json() as Promise<InAppTemplatesPaginated>;
  }

  /**
   * Create In-App Template
   */
  async createInAppTemplate(params: MarketingCreateInAppTemplateParams): Promise<CreateResult> {
    const url = `${this.baseUrl}/unified/marketing/templates/in_app`;
    const headers: Record<string, string> = {
      ...this.headers,
      'Content-Type': 'application/json',
    };
    const options: RequestInit = {
      method: 'POST',
      headers,
      body: params.body ? JSON.stringify(params.body) : undefined,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return response.json() as Promise<CreateResult>;
  }

  /**
   * Get In-App Template
   */
  async getInAppTemplate(params: MarketingGetInAppTemplateParams): Promise<InAppTemplateResult> {
    let url = `${this.baseUrl}/unified/marketing/templates/in_app/${params.id}`;
    const queryParts: string[] = [];
    if (params.raw !== undefined) {
      queryParts.push(`raw=${encodeURIComponent(String(params.raw))}`);
    }
    if (params.proxy !== undefined) {
      for (const [key, value] of Object.entries(params.proxy as Record<string, unknown>)) {
        if (value !== undefined && value !== null) {
          queryParts.push(`proxy[${key}]=${encodeURIComponent(String(value))}`);
        }
      }
    }
    if (params.fields !== undefined) {
      queryParts.push(`fields=${encodeURIComponent(String(params.fields))}`);
    }
    if (queryParts.length > 0) url += `?${queryParts.join('&')}`;
    const headers: Record<string, string> = {
      ...this.headers,
    };
    const options: RequestInit = {
      method: 'GET',
      headers,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return response.json() as Promise<InAppTemplateResult>;
  }

  /**
   * Update In-App Template
   */
  async updateInAppTemplate(params: MarketingUpdateInAppTemplateParams): Promise<CreateResult> {
    const url = `${this.baseUrl}/unified/marketing/templates/in_app/${params.id}`;
    const headers: Record<string, string> = {
      ...this.headers,
      'Content-Type': 'application/json',
    };
    const options: RequestInit = {
      method: 'PATCH',
      headers,
      body: params.body ? JSON.stringify(params.body) : undefined,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return response.json() as Promise<CreateResult>;
  }

  /**
   * List SMS Templates
   */
  async listSmsTemplates(params?: MarketingListSmsTemplatesParams): Promise<SmsTemplatesPaginated> {
    let url = `${this.baseUrl}/unified/marketing/templates/sms`;
    const queryParts: string[] = [];
    if (params?.raw !== undefined) {
      queryParts.push(`raw=${encodeURIComponent(String(params?.raw))}`);
    }
    if (params?.proxy !== undefined) {
      for (const [key, value] of Object.entries(params?.proxy as Record<string, unknown>)) {
        if (value !== undefined && value !== null) {
          queryParts.push(`proxy[${key}]=${encodeURIComponent(String(value))}`);
        }
      }
    }
    if (params?.fields !== undefined) {
      queryParts.push(`fields=${encodeURIComponent(String(params?.fields))}`);
    }
    if (params?.filter !== undefined) {
      queryParts.push(`filter=${encodeURIComponent(String(params?.filter))}`);
    }
    if (params?.pageSize !== undefined) {
      queryParts.push(`page_size=${encodeURIComponent(String(params?.pageSize))}`);
    }
    if (params?.next !== undefined) {
      queryParts.push(`next=${encodeURIComponent(String(params?.next))}`);
    }
    if (queryParts.length > 0) url += `?${queryParts.join('&')}`;
    const headers: Record<string, string> = {
      ...this.headers,
    };
    const options: RequestInit = {
      method: 'GET',
      headers,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return response.json() as Promise<SmsTemplatesPaginated>;
  }

  /**
   * Create SMS Template
   */
  async createSmsTemplate(params: MarketingCreateSmsTemplateParams): Promise<CreateResult> {
    const url = `${this.baseUrl}/unified/marketing/templates/sms`;
    const headers: Record<string, string> = {
      ...this.headers,
      'Content-Type': 'application/json',
    };
    const options: RequestInit = {
      method: 'POST',
      headers,
      body: params.body ? JSON.stringify(params.body) : undefined,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return response.json() as Promise<CreateResult>;
  }

  /**
   * Get SMS Template
   */
  async getSmsTemplate(params: MarketingGetSmsTemplateParams): Promise<SmsTemplateResult> {
    let url = `${this.baseUrl}/unified/marketing/templates/sms/${params.id}`;
    const queryParts: string[] = [];
    if (params.raw !== undefined) {
      queryParts.push(`raw=${encodeURIComponent(String(params.raw))}`);
    }
    if (params.proxy !== undefined) {
      for (const [key, value] of Object.entries(params.proxy as Record<string, unknown>)) {
        if (value !== undefined && value !== null) {
          queryParts.push(`proxy[${key}]=${encodeURIComponent(String(value))}`);
        }
      }
    }
    if (params.fields !== undefined) {
      queryParts.push(`fields=${encodeURIComponent(String(params.fields))}`);
    }
    if (queryParts.length > 0) url += `?${queryParts.join('&')}`;
    const headers: Record<string, string> = {
      ...this.headers,
    };
    const options: RequestInit = {
      method: 'GET',
      headers,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return response.json() as Promise<SmsTemplateResult>;
  }

  /**
   * Update SMS Template
   */
  async updateSmsTemplate(params: MarketingUpdateSmsTemplateParams): Promise<CreateResult> {
    const url = `${this.baseUrl}/unified/marketing/templates/sms/${params.id}`;
    const headers: Record<string, string> = {
      ...this.headers,
      'Content-Type': 'application/json',
    };
    const options: RequestInit = {
      method: 'PATCH',
      headers,
      body: params.body ? JSON.stringify(params.body) : undefined,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return response.json() as Promise<CreateResult>;
  }

  /**
   * List Push Templates
   */
  async listPushTemplates(
    params?: MarketingListPushTemplatesParams
  ): Promise<PushTemplatesPaginated> {
    let url = `${this.baseUrl}/unified/marketing/templates/push`;
    const queryParts: string[] = [];
    if (params?.raw !== undefined) {
      queryParts.push(`raw=${encodeURIComponent(String(params?.raw))}`);
    }
    if (params?.proxy !== undefined) {
      for (const [key, value] of Object.entries(params?.proxy as Record<string, unknown>)) {
        if (value !== undefined && value !== null) {
          queryParts.push(`proxy[${key}]=${encodeURIComponent(String(value))}`);
        }
      }
    }
    if (params?.fields !== undefined) {
      queryParts.push(`fields=${encodeURIComponent(String(params?.fields))}`);
    }
    if (params?.filter !== undefined) {
      queryParts.push(`filter=${encodeURIComponent(String(params?.filter))}`);
    }
    if (params?.pageSize !== undefined) {
      queryParts.push(`page_size=${encodeURIComponent(String(params?.pageSize))}`);
    }
    if (params?.next !== undefined) {
      queryParts.push(`next=${encodeURIComponent(String(params?.next))}`);
    }
    if (queryParts.length > 0) url += `?${queryParts.join('&')}`;
    const headers: Record<string, string> = {
      ...this.headers,
    };
    const options: RequestInit = {
      method: 'GET',
      headers,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return response.json() as Promise<PushTemplatesPaginated>;
  }

  /**
   * Create Push Template
   */
  async createPushTemplate(params: MarketingCreatePushTemplateParams): Promise<CreateResult> {
    const url = `${this.baseUrl}/unified/marketing/templates/push`;
    const headers: Record<string, string> = {
      ...this.headers,
      'Content-Type': 'application/json',
    };
    const options: RequestInit = {
      method: 'POST',
      headers,
      body: params.body ? JSON.stringify(params.body) : undefined,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return response.json() as Promise<CreateResult>;
  }

  /**
   * Get Push Template
   */
  async getPushTemplate(params: MarketingGetPushTemplateParams): Promise<PushTemplateResult> {
    let url = `${this.baseUrl}/unified/marketing/templates/push/${params.id}`;
    const queryParts: string[] = [];
    if (params.raw !== undefined) {
      queryParts.push(`raw=${encodeURIComponent(String(params.raw))}`);
    }
    if (params.proxy !== undefined) {
      for (const [key, value] of Object.entries(params.proxy as Record<string, unknown>)) {
        if (value !== undefined && value !== null) {
          queryParts.push(`proxy[${key}]=${encodeURIComponent(String(value))}`);
        }
      }
    }
    if (params.fields !== undefined) {
      queryParts.push(`fields=${encodeURIComponent(String(params.fields))}`);
    }
    if (queryParts.length > 0) url += `?${queryParts.join('&')}`;
    const headers: Record<string, string> = {
      ...this.headers,
    };
    const options: RequestInit = {
      method: 'GET',
      headers,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return response.json() as Promise<PushTemplateResult>;
  }

  /**
   * Update Push Template
   */
  async updatePushTemplate(params: MarketingUpdatePushTemplateParams): Promise<CreateResult> {
    const url = `${this.baseUrl}/unified/marketing/templates/push/${params.id}`;
    const headers: Record<string, string> = {
      ...this.headers,
      'Content-Type': 'application/json',
    };
    const options: RequestInit = {
      method: 'PATCH',
      headers,
      body: params.body ? JSON.stringify(params.body) : undefined,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return response.json() as Promise<CreateResult>;
  }

  /**
   * List campaigns
   */
  async listCampaigns(params?: MarketingListCampaignsParams): Promise<CampaignsPaginated> {
    let url = `${this.baseUrl}/unified/marketing/campaigns`;
    const queryParts: string[] = [];
    if (params?.raw !== undefined) {
      queryParts.push(`raw=${encodeURIComponent(String(params?.raw))}`);
    }
    if (params?.proxy !== undefined) {
      for (const [key, value] of Object.entries(params?.proxy as Record<string, unknown>)) {
        if (value !== undefined && value !== null) {
          queryParts.push(`proxy[${key}]=${encodeURIComponent(String(value))}`);
        }
      }
    }
    if (params?.fields !== undefined) {
      queryParts.push(`fields=${encodeURIComponent(String(params?.fields))}`);
    }
    if (params?.filter !== undefined) {
      queryParts.push(`filter=${encodeURIComponent(String(params?.filter))}`);
    }
    if (params?.pageSize !== undefined) {
      queryParts.push(`page_size=${encodeURIComponent(String(params?.pageSize))}`);
    }
    if (params?.next !== undefined) {
      queryParts.push(`next=${encodeURIComponent(String(params?.next))}`);
    }
    if (queryParts.length > 0) url += `?${queryParts.join('&')}`;
    const headers: Record<string, string> = {
      ...this.headers,
    };
    const options: RequestInit = {
      method: 'GET',
      headers,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return response.json() as Promise<CampaignsPaginated>;
  }

  /**
   * Get campaign
   */
  async getCampaign(params: MarketingGetCampaignParams): Promise<CampaignResult> {
    let url = `${this.baseUrl}/unified/marketing/campaigns/${params.id}`;
    const queryParts: string[] = [];
    if (params.raw !== undefined) {
      queryParts.push(`raw=${encodeURIComponent(String(params.raw))}`);
    }
    if (params.proxy !== undefined) {
      for (const [key, value] of Object.entries(params.proxy as Record<string, unknown>)) {
        if (value !== undefined && value !== null) {
          queryParts.push(`proxy[${key}]=${encodeURIComponent(String(value))}`);
        }
      }
    }
    if (params.fields !== undefined) {
      queryParts.push(`fields=${encodeURIComponent(String(params.fields))}`);
    }
    if (queryParts.length > 0) url += `?${queryParts.join('&')}`;
    const headers: Record<string, string> = {
      ...this.headers,
    };
    const options: RequestInit = {
      method: 'GET',
      headers,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return response.json() as Promise<CampaignResult>;
  }

  /**
   * List Content Blocks
   */
  async listContentBlocks(
    params?: MarketingListContentBlocksParams
  ): Promise<ContentBlocksPaginated> {
    let url = `${this.baseUrl}/unified/marketing/content_blocks`;
    const queryParts: string[] = [];
    if (params?.raw !== undefined) {
      queryParts.push(`raw=${encodeURIComponent(String(params?.raw))}`);
    }
    if (params?.proxy !== undefined) {
      for (const [key, value] of Object.entries(params?.proxy as Record<string, unknown>)) {
        if (value !== undefined && value !== null) {
          queryParts.push(`proxy[${key}]=${encodeURIComponent(String(value))}`);
        }
      }
    }
    if (params?.fields !== undefined) {
      queryParts.push(`fields=${encodeURIComponent(String(params?.fields))}`);
    }
    if (params?.filter !== undefined) {
      queryParts.push(`filter=${encodeURIComponent(String(params?.filter))}`);
    }
    if (params?.pageSize !== undefined) {
      queryParts.push(`page_size=${encodeURIComponent(String(params?.pageSize))}`);
    }
    if (params?.next !== undefined) {
      queryParts.push(`next=${encodeURIComponent(String(params?.next))}`);
    }
    if (queryParts.length > 0) url += `?${queryParts.join('&')}`;
    const headers: Record<string, string> = {
      ...this.headers,
    };
    const options: RequestInit = {
      method: 'GET',
      headers,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return response.json() as Promise<ContentBlocksPaginated>;
  }

  /**
   * Create Content Block
   */
  async createContentBlock(params: MarketingCreateContentBlockParams): Promise<CreateResult> {
    const url = `${this.baseUrl}/unified/marketing/content_blocks`;
    const headers: Record<string, string> = {
      ...this.headers,
      'Content-Type': 'application/json',
    };
    const options: RequestInit = {
      method: 'POST',
      headers,
      body: params.body ? JSON.stringify(params.body) : undefined,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return response.json() as Promise<CreateResult>;
  }

  /**
   * Get Content Blocks
   */
  async getContentBlock(params: MarketingGetContentBlockParams): Promise<ContentBlockResult> {
    let url = `${this.baseUrl}/unified/marketing/content_blocks/${params.id}`;
    const queryParts: string[] = [];
    if (params.raw !== undefined) {
      queryParts.push(`raw=${encodeURIComponent(String(params.raw))}`);
    }
    if (params.proxy !== undefined) {
      for (const [key, value] of Object.entries(params.proxy as Record<string, unknown>)) {
        if (value !== undefined && value !== null) {
          queryParts.push(`proxy[${key}]=${encodeURIComponent(String(value))}`);
        }
      }
    }
    if (params.fields !== undefined) {
      queryParts.push(`fields=${encodeURIComponent(String(params.fields))}`);
    }
    if (queryParts.length > 0) url += `?${queryParts.join('&')}`;
    const headers: Record<string, string> = {
      ...this.headers,
    };
    const options: RequestInit = {
      method: 'GET',
      headers,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return response.json() as Promise<ContentBlockResult>;
  }

  /**
   * Update Content Block
   */
  async updateContentBlock(params: MarketingUpdateContentBlockParams): Promise<CreateResult> {
    const url = `${this.baseUrl}/unified/marketing/content_blocks/${params.id}`;
    const headers: Record<string, string> = {
      ...this.headers,
      'Content-Type': 'application/json',
    };
    const options: RequestInit = {
      method: 'PATCH',
      headers,
      body: params.body ? JSON.stringify(params.body) : undefined,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return response.json() as Promise<CreateResult>;
  }
}
