// Auto-generated TypeScript SDK from OpenAPI specification
// DO NOT EDIT THIS FILE DIRECTLY

import type { StackOneClientConfig } from './types';

// ============================================================
// Type Definitions
// ============================================================

// Auto-generated TypeScript interfaces from OpenAPI schemas
// DO NOT EDIT THIS FILE DIRECTLY

export interface ActionMetaItem {
  /** The action ID */
  id?: string | null;
  /** The action label */
  label?: string | null;
  /** The action description */
  description?: string | null;
  /** The schema type for the action */
  schema_type?: string | null;
  /** The tags associated with this action */
  tags?: string[] | null;
  /** The authentication methods supported by this action */
  authentication?: AuthenticationMetaItem[] | null;
  /** The operation details for the action */
  operation_details?: Record<string, unknown> | null;
}

export interface ActionsMeta {
  /** The version of the actions metadata */
  version?: string | null;
  /** The name of the provider */
  name?: string | null;
  /** The unique key for the provider */
  key?: string | null;
  /** The icon URL for the provider */
  icon?: string | null;
  /** The description of the provider */
  description?: string | null;
  /** The authentication methods supported by the provider */
  authentication?: AuthenticationMetaItem[] | null;
  /** The list of actions available for this provider */
  actions?: ActionMetaItem[] | null;
}

export interface ActionsMetaPaginated {
  /** Cursor for fetching the next page of results */
  next?: string | null;
  /** The list of actions metadata */
  data?: ActionsMeta[] | null;
}

export interface ActionsRpcQueryDto {
  /** Enable debug mode for the action execution */
  debug?: boolean | null;
}

export interface ActionsRpcRequestDto {
  /** The action to execute */
  action: string;
  /** Path parameters for the action */
  path?: Record<string, unknown> | null;
  /** Query parameters for the action */
  query?: ActionsRpcQueryDto | null;
  /** Headers for the action */
  headers?: Record<string, unknown> | null;
  /** Request body for the action */
  body?: Record<string, unknown> | null;
}

export interface ActionsRpcResponse {
  /** Cursor for fetching the next page of results */
  next?: string | null;
  /** The response data from the action RPC call */
  data?: (Record<string, unknown> | Record<string, unknown>[] | unknown) | null;
}

export interface AdvancedLogRequestData {
  /** The request ID */
  id?: string | null;
  /** The request method */
  method?: string | null;
  headers?: Record<string, unknown> | null;
  /** The request URL data */
  url?: AdvancedLogRequestDataUrl | null;
  body?: (string | Record<string, unknown> | string | number[] | string) | null;
}

export interface AdvancedLogRequestDataUrl {
  /** The request URL */
  url?: string | null;
  /** The request URL hostname */
  hostname?: string | null;
  /** The request path */
  path?: string | null;
  /** The request query parameters */
  query_params?: Record<string, unknown> | null;
}

export interface AdvancedLogResponseData {
  /** The response status code */
  status_code?: number | null;
  headers?: Record<string, unknown> | null;
  body?: (string | Record<string, unknown> | string | number[] | string) | null;
  /** The custom mapping errors */
  custom_mapping_errors?: CustomMappingError[] | null;
  /** The provider errors */
  provider_errors?: ProviderError[] | null;
}

export interface AuthenticationMetaItem {
  /** The authentication type */
  type?: string | null;
  /** The authentication label */
  label?: string | null;
  /** The authentication key */
  key?: string | null;
}

export interface BadGatewayResponse {
  /** HTTP status code */
  statusCode: number;
  /** Error message */
  message: string;
  /** Timestamp when the error occurred */
  timestamp: string;
}

export interface BadRequestResponse {
  /** HTTP status code */
  statusCode: number;
  /** Error message */
  message: string;
  /** Timestamp when the error occurred */
  timestamp: string;
  /** Error details */
  data?: UnifiedError | null;
  /** List of provider-specific errors */
  provider_errors?: ProviderError[] | null;
}

export interface ConflictResponse {
  /** HTTP status code */
  statusCode: number;
  /** Error message */
  message: string;
  /** Timestamp when the error occurred */
  timestamp: string;
}

export interface ConnectorsMeta {
  /** The provider key */
  provider: string;
  /** The provider human-readable label */
  provider_name: string;
  /** The provider service category */
  category:
    | 'ats'
    | 'hris'
    | 'hris-legacy'
    | 'crm'
    | 'iam'
    | 'marketing'
    | 'lms'
    | 'stackone'
    | 'documents'
    | 'ticketing'
    | 'screening'
    | 'messaging'
    | 'accounting'
    | 'scheduling';
  /** Whether this provider has been enabled on the integrations page for the current project */
  active?: boolean | null;
  models: Record<string, unknown>;
  /** Resources for this provider, such as image assets */
  resources?: ConnectorsMetaResources | null;
}

export interface ConnectorsMetaResources {
  /** Image assets for this provider */
  images?: ConnectorsMetaResourcesImagesApiModel | null;
}

export interface ConnectorsMetaResourcesImagesApiModel {
  /** URL of the square logo designed and used by StackOne for this provider */
  logo_url?: string | null;
  /** URL of the original provider logo (with logo and/or name aligned horizontally) */
  original_logo_horizontal_url?: string | null;
}

export interface ConnectSession {
  id: number;
  organization_id: number;
  project_id: string;
  categories?:
    | 'ats'
    | 'hris'
    | 'hris-legacy'
    | 'crm'
    | 'iam'
    | 'marketing'
    | 'lms'
    | 'stackone'
    | 'documents'
    | 'ticketing'
    | 'screening'
    | 'messaging'
    | 'accounting'
    | 'scheduling'
    | null[]
    | null;
  provider?: string | null;
  origin_owner_id: string;
  origin_owner_name: string;
  origin_username?: string | null;
  account_id?: string | null;
  label?: string | null;
  created_at: string;
  /** Arbitrary set of key and values defined during the session token creation. This can be used to tag an account (eg. based on their pricing plan) */
  metadata?: Record<string, unknown> | null;
  /** External trigger token to be used to trigger actions on the account */
  external_trigger_token?: string | null;
  /** The connect session account type */
  type?: 'production' | 'test' | 'unmapped_value' | null;
}

export interface ConnectSessionAuthenticate {
  /** The token to authenticate with */
  token: string;
}

export interface ConnectSessionCreate {
  /** The categories of the provider to connect to */
  categories?:
    | 'ats'
    | 'hris'
    | 'hris-legacy'
    | 'crm'
    | 'iam'
    | 'marketing'
    | 'lms'
    | 'stackone'
    | 'documents'
    | 'ticketing'
    | 'screening'
    | 'messaging'
    | 'accounting'
    | 'scheduling'
    | null[]
    | null;
  /** The provider to connect to */
  provider?: string | null;
  /** The provider version to connect to */
  provider_version?: string | null;
  /** The origin owner identifier */
  origin_owner_id: string;
  /** The origin owner name */
  origin_owner_name: string;
  /** The origin username */
  origin_username?: string | null;
  /** The unique identifier for the account associated with this connect session. When this field is present, the hub will launch in edit mode using the retrieved token. */
  account_id?: string | null;
  /** How long the session should be valid for in seconds */
  expires_in?: number | null;
  /** The metadata for the connection */
  metadata?: Record<string, unknown> | null;
  /** If set, this connect session will allow creation of multiple accounts with the same origin owner id and provider. Has no effect if account_id is set. */
  multiple?: boolean | null;
  /** The label to be applied to the account associated with this connect session. */
  label?: string | null;
  /** The connect session account type */
  type?: 'production' | 'test' | null;
}

export interface ConnectSessionTokenAuthLink {
  id: number;
  organization_id: number;
  project_id: string;
  categories?:
    | 'ats'
    | 'hris'
    | 'hris-legacy'
    | 'crm'
    | 'iam'
    | 'marketing'
    | 'lms'
    | 'stackone'
    | 'documents'
    | 'ticketing'
    | 'screening'
    | 'messaging'
    | 'accounting'
    | 'scheduling'
    | null[]
    | null;
  provider?: string | null;
  origin_owner_id: string;
  origin_owner_name: string;
  origin_username?: string | null;
  account_id?: string | null;
  label?: string | null;
  created_at: string;
  /** Arbitrary set of key and values defined during the session token creation. This can be used to tag an account (eg. based on their pricing plan) */
  metadata?: Record<string, unknown> | null;
  /** External trigger token to be used to trigger actions on the account */
  external_trigger_token?: string | null;
  /** The connect session account type */
  type?: 'production' | 'test' | 'unmapped_value' | null;
  token: string;
  auth_link_url: string;
}

export interface CustomMappingError {
  /** The custom mapping identifier */
  id?: string | null;
  /** The error message */
  message?: string | null;
  /** The target field where the error occurred */
  targetField?: string | null;
}

export interface ForbiddenResponse {
  /** HTTP status code */
  statusCode: number;
  /** Error message */
  message: string;
  /** Timestamp when the error occurred */
  timestamp: string;
}

export interface InternalServerErrorResponse {
  /** HTTP status code */
  statusCode: number;
  /** Error message */
  message: string;
  /** Timestamp when the error occurred */
  timestamp: string;
}

export interface JsonRpcMessageDto {
  /** JSON-RPC protocol version */
  jsonrpc: string;
  /** JSON-RPC method name */
  method: string;
  /** Method parameters (arbitrary JSON) */
  params?: Record<string, unknown> | null;
  /** Request id (arbitrary JSON scalar) */
  id?: Record<string, unknown>;
}

export interface LinkedAccount {
  id: string;
  provider: string;
  provider_name?: string | null;
  status: 'active' | 'inactive' | 'suspended' | 'archived' | 'expired' | 'error';
  status_reasons?: StatusReason[] | null;
  origin_owner_id: string;
  origin_owner_name: string;
  origin_username?: string | null;
  credentials?: Record<string, unknown> | null;
  setup_information?: Record<string, unknown> | null;
  label?: string | null;
  created_at: string;
  updated_at: string;
  /** The account type */
  type?: 'production' | 'test' | 'unmapped_value' | null;
}

export interface LinkedAccountMeta {
  provider: string;
  category:
    | 'ats'
    | 'hris'
    | 'hris-legacy'
    | 'crm'
    | 'iam'
    | 'marketing'
    | 'lms'
    | 'stackone'
    | 'documents'
    | 'ticketing'
    | 'screening'
    | 'messaging'
    | 'accounting'
    | 'scheduling';
  models: Record<string, unknown>;
}

export interface NotFoundResponse {
  /** HTTP status code */
  statusCode: number;
  /** Error message */
  message: string;
  /** Timestamp when the error occurred */
  timestamp: string;
}

export interface NotImplementedResponse {
  /** HTTP status code */
  statusCode: number;
  /** Error message */
  message: string;
  /** Timestamp when the error occurred */
  timestamp: string;
}

export interface PatchAccountExternalDto {
  provider?: string | null;
  origin_owner_id?: string | null;
  origin_owner_name?: string | null;
  origin_username?: string | null;
  credentials?: Record<string, unknown> | null;
  setup_information?: Record<string, unknown> | null;
  secrets?: Record<string, unknown> | null;
  authentication_config_key?: string | null;
  environment?: string | null;
  label?: Record<string, unknown> | null;
  metadata?: Record<string, unknown> | null;
  /** The account type */
  type?: 'production' | 'test' | null;
}

export interface PlatformLog {
  /** The request ID */
  request_id?: string | null;
  /** The event ISO8601 date string */
  event_datetime?: string | null;
  /** The request start time ISO8601 date string */
  start_time?: string | null;
  /** The request end time ISO8601 date string */
  end_time?: string | null;
  /** The account ID of the request */
  account_id?: string | null;
  /** The project ID of the request */
  project_id?: string | null;
  /** The requested HTTP method */
  http_method?: string | null;
  /** The requested path */
  path?: string | null;
  /** The requested URL */
  url?: string | null;
  /** The requests response status code */
  status?: number | null;
  /** The request duration in milliseconds */
  duration?: number | null;
  /** The request success flag */
  success?: boolean | null;
  /** The requested resource */
  resource?: string | null;
  /** The requested child resource */
  child_resource?: string | null;
  /** The requested sub resource */
  sub_resource?: string | null;
  /** The requested action */
  action?: string | null;
  /** The requests source type */
  source_type?: string | null;
  /** The requests source value */
  source_value?: string | null;
  /** The requests source ID */
  source_id?: string | null;
  /** The requests source IPV4 ip address */
  source_ip?: string | null;
  /** The requested category */
  category?: string | null;
}

export interface PlatformLogsPaginated {
  next?: string | null;
  data: PlatformLog[];
}

export interface PreconditionFailedResponse {
  /** HTTP status code */
  statusCode: number;
  /** Error message */
  message: string;
  /** Timestamp when the error occurred */
  timestamp: string;
}

export interface ProviderError {
  /** HTTP status code of the provider error */
  status?: number | null;
  /** URL that caused the error */
  url?: string | null;
  /** Raw error response from the provider */
  raw?: Record<string, unknown> | null;
  /** Response headers */
  headers?: Record<string, unknown> | null;
}

export interface ProviderErrorApiModel {
  status?: number | null;
  url?: string | null;
  raw?: Record<string, unknown> | null;
  headers?: Record<string, unknown> | null;
}

export interface ProxyRequestBody {
  /** The base url of the request */
  url?: string | null;
  /** The method of the request */
  method?: 'get' | 'post' | 'put' | 'delete' | 'patch' | null;
  /** The path of the request including any query parameters */
  path?: string | null;
  /** The headers to send in the request */
  headers?: Record<string, unknown> | null;
  /** The body of the request */
  body?: Record<string, unknown> | null;
}

export interface ProxyResponseApiModel {
  /** The HTTP status code returned by the provider */
  status: number;
  /** The headers returned by the provider */
  headers?: Record<string, unknown> | null;
  /** The response data from the provider. Can be an object, array, or primitive value. */
  data?: (Record<string, unknown> | Record<string, unknown>[] | string | number | boolean) | null;
  /** Provider-specific errors if any occurred */
  provider_errors?: ProviderErrorApiModel[] | null;
}

export interface RequestTimedOutResponse {
  /** HTTP status code */
  statusCode: number;
  /** Error message */
  message: string;
  /** Timestamp when the error occurred */
  timestamp: string;
}

export interface StatusReason {
  code?: string | null;
  description?: string | null;
  timestamp: string;
}

export interface StepLog {
  /** The request ID */
  request_id?: string | null;
  /** The request start time ISO8601 date string */
  start_time?: string | null;
  /** The request end time ISO8601 date string */
  end_time?: string | null;
  /** The account ID of the request */
  account_id?: string | null;
  /** The project ID of the request */
  project_id?: string | null;
  /** The requested HTTP method */
  http_method?: string | null;
  /** The requested path */
  path?: string | null;
  /** The requested URL */
  url?: string | null;
  /** The requests response status code */
  status?: number | null;
  /** The request duration in milliseconds */
  duration?: number | null;
  /** The request success flag */
  success?: boolean | null;
  /** The requested provider */
  provider?: string | null;
  /** The requested service */
  service?: string | null;
  /** The requested resource */
  resource?: string | null;
  /** The requested child resource */
  child_resource?: string | null;
  /** The requested sub resource */
  sub_resource?: string | null;
  /** The requested action */
  action?: string | null;
  /** The asynchronous worker flag */
  is_worker?: boolean | null;
  /** The requests source IPV4 ip address */
  source_ip?: string | null;
  /** The provider request ID */
  id?: string | null;
  /** The advanced log request data */
  request?: AdvancedLogRequestData | null;
  /** The advanced log response data */
  response?: AdvancedLogResponseData | null;
}

export interface StepLogPartial {
  /** The request ID */
  request_id?: string | null;
  /** The request start time ISO8601 date string */
  start_time?: string | null;
  /** The request end time ISO8601 date string */
  end_time?: string | null;
  /** The account ID of the request */
  account_id?: string | null;
  /** The project ID of the request */
  project_id?: string | null;
  /** The requested HTTP method */
  http_method?: string | null;
  /** The requested path */
  path?: string | null;
  /** The requested URL */
  url?: string | null;
  /** The requests response status code */
  status?: number | null;
  /** The request duration in milliseconds */
  duration?: number | null;
  /** The request success flag */
  success?: boolean | null;
  /** The requested provider */
  provider?: string | null;
  /** The requested service */
  service?: string | null;
  /** The requested resource */
  resource?: string | null;
  /** The requested child resource */
  child_resource?: string | null;
  /** The requested sub resource */
  sub_resource?: string | null;
  /** The requested action */
  action?: string | null;
  /** The asynchronous worker flag */
  is_worker?: boolean | null;
  /** The provider request ID */
  id?: string | null;
}

export interface StepLogsPaginated {
  next?: string | null;
  data: StepLogPartial[];
}

export interface TooManyRequestsResponse {
  /** HTTP status code */
  statusCode: number;
  /** Error message */
  message: string;
  /** Timestamp when the error occurred */
  timestamp: string;
}

export interface UnauthorizedResponse {
  /** HTTP status code */
  statusCode: number;
  /** Error message */
  message: string;
  /** Timestamp when the error occurred */
  timestamp: string;
}

export interface UnifiedError {
  /** HTTP status code */
  statusCode?: number | null;
  /** Error message */
  message?: string | null;
  /** Response headers */
  headers?: Record<string, unknown> | null;
}

export interface UnifiedLogResult {
  data: UnifiedLogs;
}

export interface UnifiedLogs {
  /** The request ID */
  request_id?: string | null;
  /** The event ISO8601 date string */
  event_datetime?: string | null;
  /** The request start time ISO8601 date string */
  start_time?: string | null;
  /** The request end time ISO8601 date string */
  end_time?: string | null;
  /** The account ID of the request */
  account_id?: string | null;
  /** The project ID of the request */
  project_id?: string | null;
  /** The requested HTTP method */
  http_method?: string | null;
  /** The requested path */
  path?: string | null;
  /** The requested URL */
  url?: string | null;
  /** The requests response status code */
  status?: number | null;
  /** The request duration in milliseconds */
  duration?: number | null;
  /** The request success flag */
  success?: boolean | null;
  /** The requested provider */
  provider?: string | null;
  /** The requested service */
  service?: string | null;
  /** The requested resource */
  resource?: string | null;
  /** The requested child resource */
  child_resource?: string | null;
  /** The requested sub resource */
  sub_resource?: string | null;
  /** The requested action */
  action?: string | null;
  /** The asynchronous worker flag */
  is_worker?: boolean | null;
  /** The requests source type */
  source_type?: string | null;
  /** The requests source value */
  source_value?: string | null;
  /** The requests source ID */
  source_id?: string | null;
  /** The advanced log request data */
  request?: AdvancedLogRequestData | null;
  /** The advanced log response data */
  response?: AdvancedLogResponseData | null;
  /** The requests source IPV4 ip address */
  source_ip?: string | null;
  /** The list of provider requests */
  step_requests?: StepLog[] | null;
}

export interface UnifiedLogsPaginated {
  next?: string | null;
  data: UnifiedLogsPartial[];
}

export interface UnifiedLogsPartial {
  /** The request ID */
  request_id?: string | null;
  /** The event ISO8601 date string */
  event_datetime?: string | null;
  /** The request start time ISO8601 date string */
  start_time?: string | null;
  /** The request end time ISO8601 date string */
  end_time?: string | null;
  /** The account ID of the request */
  account_id?: string | null;
  /** The project ID of the request */
  project_id?: string | null;
  /** The requested HTTP method */
  http_method?: string | null;
  /** The requested path */
  path?: string | null;
  /** The requested URL */
  url?: string | null;
  /** The requests response status code */
  status?: number | null;
  /** The request duration in milliseconds */
  duration?: number | null;
  /** The request success flag */
  success?: boolean | null;
  /** The requested provider */
  provider?: string | null;
  /** The requested service */
  service?: string | null;
  /** The requested resource */
  resource?: string | null;
  /** The requested child resource */
  child_resource?: string | null;
  /** The requested sub resource */
  sub_resource?: string | null;
  /** The requested action */
  action?: string | null;
  /** The asynchronous worker flag */
  is_worker?: boolean | null;
  /** The requests source type */
  source_type?: string | null;
  /** The requests source value */
  source_value?: string | null;
  /** The requests source ID */
  source_id?: string | null;
  /** The requests source IPV4 ip address */
  source_ip?: string | null;
  /** The list of provider requests */
  step_requests?: StepLogPartial[] | null;
}

export interface UnprocessableEntityResponse {
  /** HTTP status code */
  statusCode: number;
  /** Error message */
  message: string;
  /** Timestamp when the error occurred */
  timestamp: string;
}

// ============================================================
// Client Class
// ============================================================

export interface StackoneCreateConnectSessionParams {
  body: ConnectSessionCreate;
}

export interface StackoneAuthenticateConnectSessionParams {
  /** The parameters to authenticate */
  body: ConnectSessionAuthenticate;
}

export interface StackoneListLinkedAccountsParams {
  /** The page number of the results to fetch */
  page?: number | null;
  /** The number of results per page */
  pageSize?: number | null;
  /** The origin owner identifier of the results to fetch */
  originOwnerId?: string | null;
  /** The origin owner identifiers of the results to fetch (supports multiple IDs) */
  originOwnerIds?: string[];
  /** The providers list of the results to fetch */
  providers?: string[];
  /** The providers list of the results to fetch */
  accountIds?: string[];
  /** The status of the results to fetch */
  status?: string[];
}

export interface StackoneGetAccountParams {
  id: string;
}

export interface StackoneDeleteAccountParams {
  id: string;
}

export interface StackoneUpdateAccountParams {
  id: string;
  body: PatchAccountExternalDto;
}

export interface StackoneGetAccountMetaInfoParams {
  id: string;
}

export interface StackoneListStepLogsParams {
  /** The field to order the results by. */
  orderBy?: 'provider' | 'service' | 'status' | 'eventDatetime' | 'duration' | null;
  /** The direction to order the results by. */
  orderDirection?: 'asc' | 'desc' | null;
  /** The number of results per page (default value is 25) */
  pageSize?: number | null;
  /** The unified cursor */
  next?: string | null;
  /** Filter parameters that allow greater customisation of the list response */
  filter?: {
    account_ids?: string | null;
    start_date?: string | null;
    end_date?: string | null;
    request_ids?: string | null;
    http_methods?: string | null;
    providers?: string | null;
    services?: string | null;
    resources?: string | null;
    child_resources?: string | null;
    sub_resources?: string | null;
    actions?: string | null;
    status_codes?: string | null;
    success?: boolean | null;
  } | null;
}

export interface StackoneGetLogParams {
  id: string;
  /** The include parameter allows you to include additional data in the response. */
  include?: 'step_logs' | 'advanced_logs' | null;
}

export interface StackoneListLogsParams {
  /** The field to order the results by. */
  orderBy?: 'provider' | 'service' | 'status' | 'eventDatetime' | 'duration' | null;
  /** The direction to order the results by. */
  orderDirection?: 'asc' | 'desc' | null;
  /** The number of results per page (default value is 25) */
  pageSize?: number | null;
  /** The unified cursor */
  next?: string | null;
  /** The include parameter allows you to include additional data in the response. */
  include?: 'step_logs' | null;
  /** Filter parameters that allow greater customisation of the list response */
  filter?: {
    account_ids?: string | null;
    start_date?: string | null;
    end_date?: string | null;
    request_ids?: string | null;
    source_types?: string | null;
    source_values?: string | null;
    source_ids?: string | null;
    http_methods?: string | null;
    providers?: string | null;
    services?: string | null;
    resources?: string | null;
    child_resources?: string | null;
    sub_resources?: string | null;
    actions?: string | null;
    status_codes?: string | null;
    success?: boolean | null;
    order_by?: 'provider' | 'service' | 'status' | 'eventDatetime' | 'duration' | null;
    order_direction?: 'asc' | 'desc' | null;
  } | null;
}

export interface StackoneListPlatformLogsParams {
  /** The field to order the results by. */
  orderBy?: 'provider' | 'service' | 'status' | 'eventDatetime' | 'duration' | null;
  /** The direction to order the results by. */
  orderDirection?: 'asc' | 'desc' | null;
  /** The number of results per page (default value is 25) */
  pageSize?: number | null;
  /** The unified cursor */
  next?: string | null;
  /** Filter parameters that allow greater customisation of the list response */
  filter?: {
    account_ids?: string | null;
    start_date?: string | null;
    end_date?: string | null;
    request_ids?: string | null;
    source_types?: string | null;
    source_values?: string | null;
    source_ids?: string | null;
    http_methods?: string | null;
    categories?: string | null;
    resources?: string | null;
    actions?: string | null;
    status_codes?: string | null;
    success?: boolean | null;
    order_by?: 'provider' | 'service' | 'status' | 'eventDatetime' | 'duration' | null;
    order_direction?: 'asc' | 'desc' | null;
  } | null;
}

export interface StackoneListConnectorsMetaParams {
  /** The comma separated list of data that will be included in the response */
  include?: string | null;
}

export interface StackoneGetConnectorMetaParams {
  provider: string;
  /** The comma separated list of data that will be included in the response */
  include?: string | null;
}

export interface StackoneMcpGetParams {
  /** Must be text/event-stream */
  accept: string;
  /** Session id */
  mcpSessionId: string;
}

export interface StackoneMcpPostParams {
  /** Session id; omit for initialize, include for subsequent calls */
  mcpSessionId?: string;
  /** JSON-RPC 2.0 message */
  body: JsonRpcMessageDto;
}

export interface StackoneMcpDeleteParams {
  /** Session id */
  mcpSessionId: string;
}

export interface StackoneProxyRequestParams {
  /** The request body */
  body: ProxyRequestBody;
}

export interface StackoneListActionsMetaParams {
  /** The number of results per page (default value is 25) */
  pageSize?: string | null;
  /** The unified cursor */
  next?: string | null;
  /** The relation to group the results by */
  groupBy?: string | null;
  /** Actions Metadata filters */
  filter?: {
    connectors?: string | null;
    account_ids?: string | null;
    action_key?: string | null;
  } | null;
  /** Additional data to include in the response */
  include?: 'action_details'[] | null;
}

export interface StackoneRpcActionParams {
  body: ActionsRpcRequestDto;
}

/**
 * Stackone API Client
 * Auto-generated from OpenAPI specification
 */
export class StackoneClient {
  private baseUrl: string;
  private headers: Record<string, string>;

  constructor(config: StackOneClientConfig) {
    this.baseUrl = config.baseUrl || 'https://api.stackone.com';
    const authToken = Buffer.from(`${config.apiKey}:`).toString('base64');
    this.headers = {
      Authorization: `Basic ${authToken}`,
      'x-account-id': config.accountId,
      ...config.headers,
    };
  }

  /**
   * Create Connect Session
   */
  async createConnectSession(
    params: StackoneCreateConnectSessionParams
  ): Promise<ConnectSessionTokenAuthLink> {
    const url = `${this.baseUrl}/connect_sessions`;
    const headers: Record<string, string> = {
      ...this.headers,
      'Content-Type': 'application/json',
    };
    const options: RequestInit = {
      method: 'POST',
      headers,
      body: params.body ? JSON.stringify(params.body) : undefined,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return response.json() as Promise<ConnectSessionTokenAuthLink>;
  }

  /**
   * Authenticate Connect Session
   */
  async authenticateConnectSession(
    params: StackoneAuthenticateConnectSessionParams
  ): Promise<ConnectSession> {
    const url = `${this.baseUrl}/connect_sessions/authenticate`;
    const headers: Record<string, string> = {
      ...this.headers,
      'Content-Type': 'application/json',
    };
    const options: RequestInit = {
      method: 'POST',
      headers,
      body: params.body ? JSON.stringify(params.body) : undefined,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return response.json() as Promise<ConnectSession>;
  }

  /**
   * List Accounts
   */
  async listLinkedAccounts(params?: StackoneListLinkedAccountsParams): Promise<LinkedAccount[]> {
    let url = `${this.baseUrl}/accounts`;
    const queryParts: string[] = [];
    if (params?.page !== undefined) {
      queryParts.push(`page=${encodeURIComponent(String(params?.page))}`);
    }
    if (params?.pageSize !== undefined) {
      queryParts.push(`page_size=${encodeURIComponent(String(params?.pageSize))}`);
    }
    if (params?.originOwnerId !== undefined) {
      queryParts.push(`origin_owner_id=${encodeURIComponent(String(params?.originOwnerId))}`);
    }
    if (params?.originOwnerIds !== undefined) {
      queryParts.push(`origin_owner_ids=${encodeURIComponent(String(params?.originOwnerIds))}`);
    }
    if (params?.providers !== undefined) {
      queryParts.push(`providers=${encodeURIComponent(String(params?.providers))}`);
    }
    if (params?.accountIds !== undefined) {
      queryParts.push(`account_ids=${encodeURIComponent(String(params?.accountIds))}`);
    }
    if (params?.status !== undefined) {
      queryParts.push(`status=${encodeURIComponent(String(params?.status))}`);
    }
    if (queryParts.length > 0) url += `?${queryParts.join('&')}`;
    const headers: Record<string, string> = {
      ...this.headers,
    };
    const options: RequestInit = {
      method: 'GET',
      headers,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return response.json() as Promise<LinkedAccount[]>;
  }

  /**
   * Get Account
   */
  async getAccount(params: StackoneGetAccountParams): Promise<LinkedAccount> {
    const url = `${this.baseUrl}/accounts/${params.id}`;
    const headers: Record<string, string> = {
      ...this.headers,
    };
    const options: RequestInit = {
      method: 'GET',
      headers,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return response.json() as Promise<LinkedAccount>;
  }

  /**
   * Delete Account
   */
  async deleteAccount(params: StackoneDeleteAccountParams): Promise<LinkedAccount> {
    const url = `${this.baseUrl}/accounts/${params.id}`;
    const headers: Record<string, string> = {
      ...this.headers,
    };
    const options: RequestInit = {
      method: 'DELETE',
      headers,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return response.json() as Promise<LinkedAccount>;
  }

  /**
   * Update Account
   */
  async updateAccount(params: StackoneUpdateAccountParams): Promise<LinkedAccount> {
    const url = `${this.baseUrl}/accounts/${params.id}`;
    const headers: Record<string, string> = {
      ...this.headers,
      'Content-Type': 'application/json',
    };
    const options: RequestInit = {
      method: 'PATCH',
      headers,
      body: params.body ? JSON.stringify(params.body) : undefined,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return response.json() as Promise<LinkedAccount>;
  }

  /**
   * Get Account Meta Information
   */
  async getAccountMetaInfo(params: StackoneGetAccountMetaInfoParams): Promise<LinkedAccountMeta> {
    const url = `${this.baseUrl}/accounts/${params.id}/meta`;
    const headers: Record<string, string> = {
      ...this.headers,
    };
    const options: RequestInit = {
      method: 'GET',
      headers,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return response.json() as Promise<LinkedAccountMeta>;
  }

  /**
   * List Step Logs
   */
  async listStepLogs(params?: StackoneListStepLogsParams): Promise<StepLogsPaginated> {
    let url = `${this.baseUrl}/requests/logs/steps`;
    const queryParts: string[] = [];
    if (params?.orderBy !== undefined) {
      queryParts.push(`order_by=${encodeURIComponent(String(params?.orderBy))}`);
    }
    if (params?.orderDirection !== undefined) {
      queryParts.push(`order_direction=${encodeURIComponent(String(params?.orderDirection))}`);
    }
    if (params?.pageSize !== undefined) {
      queryParts.push(`page_size=${encodeURIComponent(String(params?.pageSize))}`);
    }
    if (params?.next !== undefined) {
      queryParts.push(`next=${encodeURIComponent(String(params?.next))}`);
    }
    if (params?.filter !== undefined) {
      queryParts.push(`filter=${encodeURIComponent(String(params?.filter))}`);
    }
    if (queryParts.length > 0) url += `?${queryParts.join('&')}`;
    const headers: Record<string, string> = {
      ...this.headers,
    };
    const options: RequestInit = {
      method: 'GET',
      headers,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return response.json() as Promise<StepLogsPaginated>;
  }

  /**
   * Get Log
   */
  async getLog(params: StackoneGetLogParams): Promise<UnifiedLogResult> {
    let url = `${this.baseUrl}/requests/logs/${params.id}`;
    const queryParts: string[] = [];
    if (params.include !== undefined) {
      queryParts.push(`include=${encodeURIComponent(String(params.include))}`);
    }
    if (queryParts.length > 0) url += `?${queryParts.join('&')}`;
    const headers: Record<string, string> = {
      ...this.headers,
    };
    const options: RequestInit = {
      method: 'GET',
      headers,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return response.json() as Promise<UnifiedLogResult>;
  }

  /**
   * List Logs
   */
  async listLogs(params?: StackoneListLogsParams): Promise<UnifiedLogsPaginated> {
    let url = `${this.baseUrl}/requests/logs`;
    const queryParts: string[] = [];
    if (params?.orderBy !== undefined) {
      queryParts.push(`order_by=${encodeURIComponent(String(params?.orderBy))}`);
    }
    if (params?.orderDirection !== undefined) {
      queryParts.push(`order_direction=${encodeURIComponent(String(params?.orderDirection))}`);
    }
    if (params?.pageSize !== undefined) {
      queryParts.push(`page_size=${encodeURIComponent(String(params?.pageSize))}`);
    }
    if (params?.next !== undefined) {
      queryParts.push(`next=${encodeURIComponent(String(params?.next))}`);
    }
    if (params?.include !== undefined) {
      queryParts.push(`include=${encodeURIComponent(String(params?.include))}`);
    }
    if (params?.filter !== undefined) {
      queryParts.push(`filter=${encodeURIComponent(String(params?.filter))}`);
    }
    if (queryParts.length > 0) url += `?${queryParts.join('&')}`;
    const headers: Record<string, string> = {
      ...this.headers,
    };
    const options: RequestInit = {
      method: 'GET',
      headers,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return response.json() as Promise<UnifiedLogsPaginated>;
  }

  /**
   * List Platform Logs
   */
  async listPlatformLogs(params?: StackoneListPlatformLogsParams): Promise<PlatformLogsPaginated> {
    let url = `${this.baseUrl}/requests/platform-logs`;
    const queryParts: string[] = [];
    if (params?.orderBy !== undefined) {
      queryParts.push(`order_by=${encodeURIComponent(String(params?.orderBy))}`);
    }
    if (params?.orderDirection !== undefined) {
      queryParts.push(`order_direction=${encodeURIComponent(String(params?.orderDirection))}`);
    }
    if (params?.pageSize !== undefined) {
      queryParts.push(`page_size=${encodeURIComponent(String(params?.pageSize))}`);
    }
    if (params?.next !== undefined) {
      queryParts.push(`next=${encodeURIComponent(String(params?.next))}`);
    }
    if (params?.filter !== undefined) {
      queryParts.push(`filter=${encodeURIComponent(String(params?.filter))}`);
    }
    if (queryParts.length > 0) url += `?${queryParts.join('&')}`;
    const headers: Record<string, string> = {
      ...this.headers,
    };
    const options: RequestInit = {
      method: 'GET',
      headers,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return response.json() as Promise<PlatformLogsPaginated>;
  }

  /**
   * List Connector Meta Information
   */
  async listConnectorsMeta(params?: StackoneListConnectorsMetaParams): Promise<ConnectorsMeta[]> {
    let url = `${this.baseUrl}/connectors/meta`;
    const queryParts: string[] = [];
    if (params?.include !== undefined) {
      queryParts.push(`include=${encodeURIComponent(String(params?.include))}`);
    }
    if (queryParts.length > 0) url += `?${queryParts.join('&')}`;
    const headers: Record<string, string> = {
      ...this.headers,
    };
    const options: RequestInit = {
      method: 'GET',
      headers,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return response.json() as Promise<ConnectorsMeta[]>;
  }

  /**
   * Get Connector Meta Information
   */
  async getConnectorMeta(params: StackoneGetConnectorMetaParams): Promise<ConnectorsMeta> {
    let url = `${this.baseUrl}/connectors/meta/${params.provider}`;
    const queryParts: string[] = [];
    if (params.include !== undefined) {
      queryParts.push(`include=${encodeURIComponent(String(params.include))}`);
    }
    if (queryParts.length > 0) url += `?${queryParts.join('&')}`;
    const headers: Record<string, string> = {
      ...this.headers,
    };
    const options: RequestInit = {
      method: 'GET',
      headers,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return response.json() as Promise<ConnectorsMeta>;
  }

  /**
   * Open MCP SSE stream
   */
  async mcpGet(params: StackoneMcpGetParams): Promise<void> {
    const url = `${this.baseUrl}/mcp`;
    const headers: Record<string, string> = {
      ...this.headers,
    };
    if (params.accept !== undefined) {
      headers.Accept = String(params.accept);
    }
    if (params.mcpSessionId !== undefined) {
      headers['mcp-session-id'] = String(params.mcpSessionId);
    }
    const options: RequestInit = {
      method: 'GET',
      headers,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return;
  }

  /**
   * Send MCP JSON-RPC message
   */
  async mcpPost(params: StackoneMcpPostParams): Promise<void> {
    const url = `${this.baseUrl}/mcp`;
    const headers: Record<string, string> = {
      ...this.headers,
      'Content-Type': 'application/json',
    };
    if (params.mcpSessionId !== undefined) {
      headers['mcp-session-id'] = String(params.mcpSessionId);
    }
    const options: RequestInit = {
      method: 'POST',
      headers,
      body: params.body ? JSON.stringify(params.body) : undefined,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return;
  }

  /**
   * Delete MCP session
   */
  async mcpDelete(params: StackoneMcpDeleteParams): Promise<void> {
    const url = `${this.baseUrl}/mcp`;
    const headers: Record<string, string> = {
      ...this.headers,
    };
    if (params.mcpSessionId !== undefined) {
      headers['mcp-session-id'] = String(params.mcpSessionId);
    }
    const options: RequestInit = {
      method: 'DELETE',
      headers,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return;
  }

  /**
   * Proxy Request
   */
  async proxyRequest(params: StackoneProxyRequestParams): Promise<ProxyResponseApiModel> {
    const url = `${this.baseUrl}/unified/proxy`;
    const headers: Record<string, string> = {
      ...this.headers,
      'Content-Type': 'application/json',
    };
    const options: RequestInit = {
      method: 'POST',
      headers,
      body: params.body ? JSON.stringify(params.body) : undefined,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return response.json() as Promise<ProxyResponseApiModel>;
  }

  /**
   * List all actions metadata
   */
  async listActionsMeta(params?: StackoneListActionsMetaParams): Promise<ActionsMetaPaginated> {
    let url = `${this.baseUrl}/actions`;
    const queryParts: string[] = [];
    if (params?.pageSize !== undefined) {
      queryParts.push(`page_size=${encodeURIComponent(String(params?.pageSize))}`);
    }
    if (params?.next !== undefined) {
      queryParts.push(`next=${encodeURIComponent(String(params?.next))}`);
    }
    if (params?.groupBy !== undefined) {
      queryParts.push(`group_by=${encodeURIComponent(String(params?.groupBy))}`);
    }
    if (params?.filter !== undefined) {
      queryParts.push(`filter=${encodeURIComponent(String(params?.filter))}`);
    }
    if (params?.include !== undefined) {
      queryParts.push(`include=${encodeURIComponent(String(params?.include))}`);
    }
    if (queryParts.length > 0) url += `?${queryParts.join('&')}`;
    const headers: Record<string, string> = {
      ...this.headers,
    };
    const options: RequestInit = {
      method: 'GET',
      headers,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return response.json() as Promise<ActionsMetaPaginated>;
  }

  /**
   * Make an RPC call to an action
   */
  async rpcAction(params: StackoneRpcActionParams): Promise<ActionsRpcResponse> {
    const url = `${this.baseUrl}/actions/rpc`;
    const headers: Record<string, string> = {
      ...this.headers,
      'Content-Type': 'application/json',
    };
    const options: RequestInit = {
      method: 'POST',
      headers,
      body: params.body ? JSON.stringify(params.body) : undefined,
    };
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API error ${response.status}: ${errorBody}`);
    }
    return response.json() as Promise<ActionsRpcResponse>;
  }
}
