// Auto-generated shared types
// DO NOT EDIT THIS FILE DIRECTLY

/**
 * Configuration for StackOne API clients
 */
export interface StackOneClientConfig {
  /** StackOne API key */
  apiKey: string;
  /** Account ID for the linked account */
  accountId: string;
  /** Base URL for the API (defaults to https://api.stackone.com) */
  baseUrl?: string;
  /** Additional headers to include in requests */
  headers?: Record<string, string>;
}
