name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}

      - name: Install bun
        if: ${{ steps.release.outputs.release_created }}
        uses: oven-sh/setup-bun@v2

      - name: Install Node
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: bun install

      - name: Build package
        if: ${{ steps.release.outputs.release_created }}
        run: bun run build

      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_CONFIG_TOKEN }}

      - name: Publish package
        run: npm publish --access public
